// This file is auto-generated by scripts/generate-swagger-docs.ts
// Do not edit manually
export const swaggerHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demon List VN v3 REST API Docs</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui.css">
    <style>
        body {
            margin: 0;
            padding: 0;
        }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            const spec = {
  "openapi": "3.0.0",
  "info": {
    "title": "Demon List VN v3 REST API Docs",
    "version": "1.0.0"
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/APIKey": {
      "get": {
        "tags": [
          "API Key"
        ],
        "summary": "Get all API keys for the authenticated user",
        "responses": {
          "200": {
            "description": "Success - returns an array of API keys"
          },
          "403": {
            "description": "Forbidden - API key authentication cannot be used for this endpoint"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "API Key"
        ],
        "summary": "Create a new API key for the authenticated user",
        "responses": {
          "200": {
            "description": "Success - a new API key has been created"
          },
          "403": {
            "description": "Forbidden - API key authentication cannot be used for this endpoint"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/APIKey/{key}": {
      "delete": {
        "tags": [
          "API Key"
        ],
        "summary": "Delete a specific API key for the authenticated user",
        "parameters": [
          {
            "name": "key",
            "in": "path",
            "description": "The API key to delete",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success - the API key has been deleted"
          },
          "403": {
            "description": "Forbidden - API key authentication cannot be used for this endpoint"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/auth/callback/discord": {
      "get": {
        "summary": "Discord OAuth callback",
        "tags": [
          "Auth"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "code",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Authorization code from Discord"
          }
        ],
        "responses": {
          "200": {
            "description": "Redirects to the Discord link page with access token"
          },
          "401": {
            "description": "Unauthorized, invalid authorization code"
          }
        }
      }
    },
    "/auth/link/discord": {
      "patch": {
        "summary": "Link Discord account to user",
        "tags": [
          "Auth"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "token",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Discord access token"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully linked Discord account"
          },
          "401": {
            "description": "Unauthorized, invalid access token"
          }
        }
      }
    },
    "/auth/link/pointercrate": {
      "patch": {
        "summary": "Link Pointercrate account to user",
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string",
                    "description": "Pointercrate access token"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully linked Pointercrate account"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/card/{id}": {
      "get": {
        "tags": [
          "Card"
        ],
        "summary": "Get card by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the card",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/card/{id}/link": {
      "patch": {
        "tags": [
          "Card"
        ],
        "summary": "Link a card to user account",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the card",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Card linked successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/card/{id}/content": {
      "patch": {
        "tags": [
          "Card"
        ],
        "summary": "Update card content",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the card",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Card content updated successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/changelogs/publish": {
      "post": {
        "tags": [
          "Changelogs"
        ],
        "summary": "Publish pending changelogs",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Changelogs published successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/clans": {
      "get": {
        "tags": [
          "Clan"
        ],
        "summary": "Get clan list",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "name"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": true
            }
          },
          {
            "name": "searchQuery",
            "in": "query",
            "description": "Search query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/clan": {
      "post": {
        "tags": [
          "Clan"
        ],
        "summary": "Create a new clan",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/invitations": {
      "get": {
        "tags": [
          "Clan"
        ],
        "summary": "Get all invitations sent by clan",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ]
      }
    },
    "/clan/{id}": {
      "get": {
        "tags": [
          "Clan"
        ],
        "summary": "Get a single clan by the id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      },
      "patch": {
        "tags": [
          "Clan"
        ],
        "summary": "Edit a clan owned by user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "delete": {
        "tags": [
          "Clan"
        ],
        "summary": "Delete a clan owned by user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/{id}/members": {
      "get": {
        "tags": [
          "Clan"
        ],
        "summary": "Get member list of a clan",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "rating"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/clan/{id}/records": {
      "get": {
        "tags": [
          "Clan"
        ],
        "summary": "Get record list of a clan",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "dlPt"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/clan/invite/{uid}": {
      "post": {
        "tags": [
          "Clan"
        ],
        "summary": "Invite a player to a clan by the uid",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/{id}/invite": {
      "patch": {
        "tags": [
          "Clan"
        ],
        "summary": "Accept a clan invitation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "delete": {
        "tags": [
          "Clan"
        ],
        "summary": "Reject a clan invitation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/leave": {
      "put": {
        "tags": [
          "Clan"
        ],
        "summary": "Leave joined clan",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/{id}/join": {
      "put": {
        "tags": [
          "Clan"
        ],
        "summary": "Join a clan",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/{id}/invitation/{uid}": {
      "get": {
        "tags": [
          "Clan"
        ],
        "summary": "Get an invitation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "delete": {
        "tags": [
          "Clan"
        ],
        "summary": "Delete an invitation",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/{id}/kick/{uid}": {
      "patch": {
        "tags": [
          "Clan"
        ],
        "summary": "Kick a player",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the clan",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/clan/{id}/ban/{uid}": {
      "post": {
        "tags": [
          "Clan"
        ],
        "summary": "Ban a user from a clan",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the clan",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "uid",
            "in": "path",
            "description": "The UID of the user to ban",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User banned successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/clan/{id}/list/{list}": {
      "get": {
        "tags": [
          "Clan"
        ],
        "summary": "Get levels completed by clan members",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the clan",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "list",
            "in": "path",
            "description": "List type (dl, pl, or fl)",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "dl",
                "pl",
                "fl"
              ]
            }
          },
          {
            "name": "from",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 0
            }
          },
          {
            "name": "to",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 49
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/coupon/{code}": {
      "get": {
        "tags": [
          "Coupon"
        ],
        "summary": "Get coupon details by code",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "code",
            "in": "path",
            "description": "The coupon code",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "delete": {
        "tags": [
          "Coupon"
        ],
        "summary": "Redeem a coupon code",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "code",
            "in": "path",
            "description": "The coupon code to redeem",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Coupon redeemed successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/deathCount/{uid}/{levelID}": {
      "get": {
        "tags": [
          "Level"
        ],
        "summary": "Get level's death count",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "levelID",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/deathCount/{levelID}/{count}": {
      "post": {
        "tags": [
          "Death count"
        ],
        "summary": "Add player's level death count",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "count",
            "in": "path",
            "description": "Serialized array string",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/events": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get all events with filters",
        "parameters": [
          {
            "name": "search",
            "in": "query",
            "description": "Search term",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "eventType",
            "in": "query",
            "description": "Event type filter",
            "required": false,
            "schema": {
              "type": "string",
              "default": "all"
            }
          },
          {
            "name": "contestType",
            "in": "query",
            "description": "Contest type filter",
            "required": false,
            "schema": {
              "type": "string",
              "default": "all"
            }
          },
          {
            "name": "from",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 0
            }
          },
          {
            "name": "to",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "integer",
              "default": 50
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "post": {
        "tags": [
          "Event"
        ],
        "summary": "Create a new event (Admin only)",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Event created successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/events/ongoing": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get ongoing events",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/events/proof": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get event proofs",
        "parameters": [
          {
            "name": "from",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "to",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/event/proof": {
      "put": {
        "tags": [
          "Event"
        ],
        "summary": "Add/Edit user's event proof",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Event"
        ],
        "summary": "Create new event proof",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/events/submitLevel/{levelID}": {
      "put": {
        "tags": [
          "Event"
        ],
        "summary": "Submit event level completion",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "levelID",
            "in": "path",
            "description": "The ID of the level",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "progress",
            "in": "query",
            "description": "Completion progress",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "password",
            "in": "query",
            "description": "Submit password for authentication",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Level submitted successfully"
          },
          "403": {
            "description": "Invalid password"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/events/quest/{questId}/check": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Check quest completion status",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "questId",
            "in": "path",
            "description": "The ID of the quest",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Quest status returned (claimed, claimable, or unclaimable)",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "enum": [
                        "claimed",
                        "claimable",
                        "unclaimable"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/events/quest/{questId}/claim": {
      "post": {
        "tags": [
          "Event"
        ],
        "summary": "Claim quest reward",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "questId",
            "in": "path",
            "description": "The ID of the quest",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Quest reward claimed successfully"
          },
          "400": {
            "description": "Quest already claimed or not completed"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/events/submission": {
      "patch": {
        "tags": [
          "Event"
        ],
        "summary": "Update event submission (Admin only)",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Submission updated successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/events/{id}": {
      "patch": {
        "tags": [
          "Event"
        ],
        "summary": "Update an event (Admin only)",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the event",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Event updated successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/event/{id}/levels": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get levels of an event",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/events/{id}/level/{levelID}": {
      "delete": {
        "tags": [
          "Event"
        ],
        "summary": "Delete a level from an event (Admin only)",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the event",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "levelID",
            "in": "path",
            "description": "The ID of the level",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Level deleted successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/event/{id}/submissions": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get submissions of an event",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/event/{id}/submit": {
      "post": {
        "tags": [
          "Event"
        ],
        "summary": "Submit an event",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/event/{id}/submission/{levelID}": {
      "delete": {
        "tags": [
          "Event"
        ],
        "summary": "Delete a submission for a specific level in an event",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "levelID",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/event/{id}/leaderboard": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get leaderboard of an event",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/event/{id}": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get event by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/event/{id}/proofs": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get event's proofs",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/event/{id}/proof/{uid}": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get user's event proof",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "uid",
            "in": "path",
            "description": "The id of the event",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Event"
        ],
        "summary": "Delete a player's event proof",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/events/{id}/calc": {
      "patch": {
        "tags": [
          "Event"
        ],
        "summary": "Calculate event leaderboard (Admin only)",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the event",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Leaderboard calculated successfully"
          },
          "403": {
            "description": "Event is unranked"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/events/{id}/quest": {
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "Get quests for an event",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the event",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/inventory": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "Get user's inventory items",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/inventory/{id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "Get a specific inventory item by ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the inventory item",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/inventory/{id}/consume": {
      "delete": {
        "tags": [
          "Inventory"
        ],
        "summary": "Consume/use an inventory item",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the inventory item to consume",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Item consumed successfully"
          },
          "404": {
            "description": "Item not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/item/{id}": {
      "get": {
        "tags": [
          "Item"
        ],
        "summary": "Get item details by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the item",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/leaderboard/dl": {
      "get": {
        "tags": [
          "Leaderboard"
        ],
        "summary": "Get leaderboard of Demon List",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "overallRank"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/leaderboard/fl": {
      "get": {
        "tags": [
          "Leaderboard"
        ],
        "summary": "Get leaderboard of Platformer List",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "flrank"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/level": {
      "put": {
        "tags": [
          "Level"
        ],
        "summary": "Add or update a level",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/levels/new": {
      "get": {
        "summary": "Get new unrated levels",
        "tags": [
          "Level"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/levels/random": {
      "get": {
        "tags": [
          "Level"
        ],
        "summary": "Get random levels",
        "parameters": [
          {
            "name": "list",
            "in": "query",
            "description": "Filter by list type (dl, fl, pl)",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "dl",
                "fl",
                "pl"
              ]
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of levels to return",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/level/{id}": {
      "get": {
        "tags": [
          "Level"
        ],
        "summary": "Get a single level by the id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Level"
        ],
        "summary": "Delete a single level by the id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/level/{id}/records": {
      "get": {
        "tags": [
          "Level"
        ],
        "summary": "Get all records of a level",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "isChecked",
            "in": "query",
            "description": "Record acception status",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/levels/{id}/inEvent": {
      "get": {
        "tags": [
          "Level"
        ],
        "summary": "Check if level is in any active events for user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the level",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "type",
            "in": "query",
            "description": "Event type filter",
            "required": false,
            "schema": {
              "type": "string",
              "default": "basic"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/list/dl": {
      "get": {
        "tags": [
          "List"
        ],
        "summary": "Get all records of the Demon List",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "dlTop"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          },
          {
            "name": "uid",
            "in": "query",
            "description": "Progress of player",
            "required": false,
            "schema": {
              "type": "string",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/list/pl": {
      "get": {
        "tags": [
          "List"
        ],
        "summary": "Get all records of the Platformer List",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "dlTop"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          },
          {
            "name": "uid",
            "in": "query",
            "description": "Progress of player",
            "required": false,
            "schema": {
              "type": "string",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/list/fl": {
      "get": {
        "tags": [
          "List"
        ],
        "summary": "Get all records of the Demon List",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "flTop"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/list/dl/records": {
      "get": {
        "tags": [
          "List"
        ],
        "summary": "Get all records of the Demon List",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "isChecked",
            "in": "query",
            "description": "Record acception status",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/list/fl/records": {
      "get": {
        "tags": [
          "List"
        ],
        "summary": "Get all records of the Featured List",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "isChecked",
            "in": "query",
            "description": "Record acception status",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/list/{list}/random": {
      "get": {
        "tags": [
          "List"
        ],
        "summary": "Get a random level from a list",
        "parameters": [
          {
            "name": "list",
            "in": "path",
            "description": "List type (dl, pl, or fl)",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "dl",
                "pl",
                "fl"
              ]
            }
          },
          {
            "name": "exclude",
            "in": "query",
            "description": "Level IDs to exclude",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success - Returns a random level object",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/merchant/orders": {
      "get": {
        "tags": [
          "Merchant"
        ],
        "summary": "Get all pending and paid orders for merchant",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/merchant/order/{id}/tracking": {
      "post": {
        "tags": [
          "Merchant"
        ],
        "summary": "Add tracking information to an order",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The order ID",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string",
                    "description": "Tracking update content"
                  },
                  "link": {
                    "type": "string",
                    "description": "Optional tracking link"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Tracking information added successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/mergeAccount/:a/:b": {
      "patch": {
        "tags": [
          "Others"
        ],
        "summary": "Merge player A to B (assign all data of A to B and delete player A)",
        "parameters": [
          {
            "name": "a",
            "in": "path",
            "description": "Player A UID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "b",
            "in": "path",
            "description": "Player B UID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/notification": {
      "post": {
        "tags": [
          "Notification"
        ],
        "summary": "Send a notification",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/notifications/{uid}": {
      "get": {
        "tags": [
          "Notification"
        ],
        "summary": "Get a player's notifications",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Notification"
        ],
        "summary": "Clear a player's notification",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/orders": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Get all orders for authenticated user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Create a new order",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "orderID": {
                          "type": "integer"
                        },
                        "productID": {
                          "type": "integer"
                        },
                        "quantity": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "address": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "integer"
                  },
                  "recipientName": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Order created successfully"
          },
          "400": {
            "description": "Missing required information"
          }
        }
      }
    },
    "/orders/{id}": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Get a specific order by ID",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the order",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/orders/getPaymentLink/{id}": {
      "get": {
        "tags": [
          "Orders"
        ],
        "summary": "Get payment link",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The ID of the order",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/payment/getPaymentLink/{productID}/{quantity}": {
      "get": {
        "tags": [
          "Payment"
        ],
        "summary": "Get payment link for a product",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "productID",
            "in": "path",
            "description": "The ID of the product",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "quantity",
            "in": "path",
            "description": "Quantity to purchase",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "giftTo",
            "in": "query",
            "description": "UID to gift the product to",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "targetClanID",
            "in": "query",
            "description": "Clan ID for clan-related products",
            "required": false,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "checkoutUrl": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/payment/getPaymentLink": {
      "post": {
        "tags": [
          "Payment"
        ],
        "summary": "Get payment link for multiple items",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "orderID": {
                          "type": "integer"
                        },
                        "productID": {
                          "type": "integer"
                        },
                        "quantity": {
                          "type": "integer"
                        }
                      }
                    }
                  },
                  "address": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "integer"
                  },
                  "recipientName": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "checkoutUrl": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing required information"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/payment/success": {
      "get": {
        "tags": [
          "Payment"
        ],
        "summary": "Callback route when payment is successful",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/payment/cancelled": {
      "get": {
        "tags": [
          "Payment"
        ],
        "summary": "Callback route when payment is cancelled",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/payment/webhook": {
      "post": {
        "tags": [
          "Payment"
        ],
        "summary": "Webhook endpoint for payment provider callbacks",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Webhook processed successfully"
          },
          "500": {
            "description": "Webhook processing failed"
          }
        }
      }
    },
    "/players": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get all players matched filter",
        "parameters": [
          {
            "name": "province",
            "in": "query",
            "description": "Province name",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "city",
            "in": "query",
            "description": "City name",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sortBy",
            "in": "query",
            "description": "Property of level to sort by",
            "required": false,
            "schema": {
              "type": "string",
              "default": "rating"
            }
          },
          {
            "name": "ascending",
            "in": "query",
            "description": "Sort ascending",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/player": {
      "put": {
        "tags": [
          "Player"
        ],
        "summary": "Add or update a Player",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/players/batch": {
      "post": {
        "tags": [
          "Player"
        ],
        "summary": "Get multiple players by UIDs",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "batch": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "description": "Array of player UIDs"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/player/{uid}": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get a single player by the uid",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/player/{uid}/records": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get all records of a player",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "isChecked",
            "in": "query",
            "description": "Record acception status",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/player/{uid}/heatmap": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get player heatmap",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "path",
            "description": "Year to fetch",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/player/heatmap/{count}": {
      "post": {
        "tags": [
          "Player"
        ],
        "summary": "Add 1 attempt to the heatmap",
        "parameters": [
          {
            "name": "count",
            "in": "path",
            "description": "Amount of attempt to add",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/{uid}/submissions": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get player's submissions",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The UID of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/player/syncRole": {
      "patch": {
        "tags": [
          "Player"
        ],
        "summary": "Synchronize the player's role to Discord",
        "responses": {
          "200": {
            "description": "Role synchronized successfully"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/{uid}/medals": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get player's medals",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The UID of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/players/{uid}/events": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get player's event proofs",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The UID of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/players/{uid}/cards": {
      "get": {
        "tags": [
          "Player"
        ],
        "summary": "Get player's supporter cards",
        "parameters": [
          {
            "name": "uid",
            "in": "path",
            "description": "The UID of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/provinces": {
      "get": {
        "tags": [
          "Others"
        ],
        "summary": "Get a list of all Vietnamese provinces and cities",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/records": {
      "get": {
        "tags": [
          "Record"
        ],
        "summary": "Get all records of all list",
        "parameters": [
          {
            "name": "start",
            "in": "query",
            "description": "Range start index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 0
            }
          },
          {
            "name": "end",
            "in": "query",
            "description": "Range end index",
            "required": false,
            "schema": {
              "type": "number",
              "default": 50
            }
          },
          {
            "name": "isChecked",
            "in": "query",
            "description": "Record acception status",
            "required": false,
            "schema": {
              "type": "boolean",
              "default": false
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/record": {
      "put": {
        "tags": [
          "Record"
        ],
        "summary": "Add or update a record",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/record/{userID}/{levelID}": {
      "delete": {
        "tags": [
          "Record"
        ],
        "summary": "Delete a single record",
        "parameters": [
          {
            "name": "userID",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "levelID",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "GET": {
        "tags": [
          "Record"
        ],
        "summary": "Get a single record",
        "parameters": [
          {
            "name": "userID",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "levelID",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/record/{userID}/{levelID}/changeSuggestedRating/{rating}": {
      "PUT": {
        "tags": [
          "Record"
        ],
        "summary": "Change suggested rating of a record",
        "parameters": [
          {
            "name": "userID",
            "in": "path",
            "description": "The uid of the player",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "levelID",
            "in": "path",
            "description": "The id of the level",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/retrieve": {
      "GET": {
        "tags": [
          "Record"
        ],
        "summary": "Retrieve a record for trusted player",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/refresh": {
      "patch": {
        "tags": [
          "Others"
        ],
        "summary": "Recalculate all player and level rank",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/rules": {
      "get": {
        "tags": [
          "Rules"
        ],
        "summary": "Get all rules",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/search/{query}": {
      "get": {
        "tags": [
          "Search"
        ],
        "summary": "Search for levels and players",
        "parameters": [
          {
            "name": "query",
            "in": "path",
            "description": "Search query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Length of result",
            "required": false,
            "schema": {
              "type": "number",
              "default": 5
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          }
        }
      }
    },
    "/storage/presign": {
      "get": {
        "tags": [
          "Storage"
        ],
        "summary": "Get a presigned URL for file upload to S3",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "path",
            "in": "query",
            "description": "File path for upload",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "bucket",
            "in": "query",
            "description": "S3 bucket name (defaults to 'cdn')",
            "required": false,
            "schema": {
              "type": "string",
              "default": "cdn"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Presigned URL generated successfully",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "400": {
            "description": "Missing file path"
          },
          "403": {
            "description": "Forbidden - user not authorized for this path"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/store/product/{id}": {
      "get": {
        "tags": [
          "Store"
        ],
        "summary": "Get a product by ID",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The product ID",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "400": {
            "description": "Invalid product ID"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/store/products": {
      "get": {
        "tags": [
          "Store"
        ],
        "summary": "Get all products or products by IDs",
        "parameters": [
          {
            "name": "ids",
            "in": "query",
            "description": "JSON array of product IDs to filter by",
            "required": false,
            "schema": {
              "type": "string",
              "example": "[1,2,3]"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": null
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/submission": {
      "POST": {
        "tags": [
          "Submission"
        ],
        "summary": "Add or edit a submission",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/submitVerdict": {
      "PUT": {
        "tags": [
          "Verdict"
        ],
        "summary": "Submit a verdict from trusted player",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": null
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "API Key",
      "description": "Endpoints for managing API keys"
    },
    {
      "name": "Auth",
      "description": "Authentication routes"
    }
  ]
};
            
            window.ui = SwaggerUIBundle({
                spec: spec,
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`;
