import swaggerJsdoc from 'swagger-jsdoc';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Swagger options configuration
const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Demon List VN v3 REST API Docs",
      version: '1.0.0',
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
  },
  apis: ["./src/routes/*.ts"],
};

// Generate Swagger specification
const swaggerSpec = swaggerJsdoc(options);

// Create static directory if it doesn't exist
const staticDir = join(__dirname, '..', 'static');
mkdirSync(staticDir, { recursive: true });

// Generate HTML content using Swagger UI standalone
const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Demon List VN v3 REST API Docs</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui.css">
    <style>
        body {
            margin: 0;
            padding: 0;
        }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            const spec = ${JSON.stringify(swaggerSpec, null, 2)};
            
            window.ui = SwaggerUIBundle({
                spec: spec,
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`;

// Write the HTML file
const outputPath = join(staticDir, 'swagger.html');
writeFileSync(outputPath, html, 'utf-8');

// Also create a TypeScript module that exports the HTML as a string
// This allows it to be imported in Cloudflare Workers environment
const tsModulePath = join(staticDir, 'swagger-html.ts');
const escapedHtml = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
const tsModule = `// This file is auto-generated by scripts/generate-swagger-docs.ts
// Do not edit manually
export const swaggerHtml = \`${escapedHtml}\`;
`;
writeFileSync(tsModulePath, tsModule, 'utf-8');

console.log(`✅ Swagger documentation generated successfully at: ${outputPath}`);
console.log(`✅ Swagger TypeScript module generated at: ${tsModulePath}`);
console.log(`📄 Total routes documented: ${Object.keys(swaggerSpec.paths || {}).length}`);
