// Script to generate pre-compiled Swagger UI HTML as a TypeScript module
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Demon List VN v3 REST API Docs</title>
  <link rel="stylesheet" type="text/css" href="/docs/swagger-ui.css" />
  <link rel="icon" type="image/png" href="/docs/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/docs/favicon-16x16.png" sizes="16x16" />
  <style>
    html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
    *, *:before, *:after { box-sizing: inherit; }
    body { margin:0; padding:0; }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="/docs/swagger-ui-bundle.js" charset="UTF-8"></script>
  <script src="/docs/swagger-ui-standalone-preset.js" charset="UTF-8"></script>
  <script>
    window.onload = function() {
      window.ui = SwaggerUIBundle({
        url: "/docs/openapi.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      });
    };
  </script>
</body>
</html>`;

// Generate a TypeScript module that exports the HTML
const tsModule = `// Auto-generated file - do not edit manually
// Generated by: npm run generate-swagger-html

export const swaggerHtml = \`${html.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;

export default swaggerHtml;
`;

// Ensure output directory exists
const outputDir = path.join(__dirname, '../static');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Write the TypeScript module
const outputPath = path.join(outputDir, 'swagger-ui.html.ts');
fs.writeFileSync(outputPath, tsModule);

console.log(`Swagger UI HTML module generated at: ${outputPath}`);
