create table "public"."changelogs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "levelID" bigint not null,
    "old" json,
    "new" json not null,
    "published" boolean default false
);


alter table "public"."changelogs" enable row level security;

CREATE UNIQUE INDEX changelogs_pkey ON public.changelogs USING btree (id);

alter table "public"."changelogs" add constraint "changelogs_pkey" PRIMARY KEY using index "changelogs_pkey";

alter table "public"."changelogs" add constraint "changelogs_levelID_fkey" FOREIGN KEY ("levelID") REFERENCES levels(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."changelogs" validate constraint "changelogs_levelID_fkey";

grant delete on table "public"."changelogs" to "anon";

grant insert on table "public"."changelogs" to "anon";

grant references on table "public"."changelogs" to "anon";

grant select on table "public"."changelogs" to "anon";

grant trigger on table "public"."changelogs" to "anon";

grant truncate on table "public"."changelogs" to "anon";

grant update on table "public"."changelogs" to "anon";

grant delete on table "public"."changelogs" to "authenticated";

grant insert on table "public"."changelogs" to "authenticated";

grant references on table "public"."changelogs" to "authenticated";

grant select on table "public"."changelogs" to "authenticated";

grant trigger on table "public"."changelogs" to "authenticated";

grant truncate on table "public"."changelogs" to "authenticated";

grant update on table "public"."changelogs" to "authenticated";

grant delete on table "public"."changelogs" to "service_role";

grant insert on table "public"."changelogs" to "service_role";

grant references on table "public"."changelogs" to "service_role";

grant select on table "public"."changelogs" to "service_role";

grant trigger on table "public"."changelogs" to "service_role";

grant truncate on table "public"."changelogs" to "service_role";

grant update on table "public"."changelogs" to "service_role";


