create table "public"."PVPPlayers" (
    "joined_at" timestamp with time zone not null default now(),
    "player" uuid not null,
    "room" bigint not null
);


alter table "public"."PVPPlayers" enable row level security;

create table "public"."PVPRooms" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "playerCount" bigint not null default '0'::bigint,
    "averageRating" bigint not null default '0'::bigint,
    "isPublic" boolean not null default false,
    "host" uuid
);


alter table "public"."PVPRooms" enable row level security;

alter table "public"."deathCount" drop column "completed";

alter table "public"."deathCount" add column "completedTime" timestamp with time zone;

CREATE UNIQUE INDEX "PVPPlayers_pkey" ON public."PVPPlayers" USING btree (player, room);

CREATE UNIQUE INDEX "PVPRoom_pkey" ON public."PVPRooms" USING btree (id);

alter table "public"."PVPPlayers" add constraint "PVPPlayers_pkey" PRIMARY KEY using index "PVPPlayers_pkey";

alter table "public"."PVPRooms" add constraint "PVPRoom_pkey" PRIMARY KEY using index "PVPRoom_pkey";

alter table "public"."PVPPlayers" add constraint "PVPPlayers_player_fkey" FOREIGN KEY (player) REFERENCES players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."PVPPlayers" validate constraint "PVPPlayers_player_fkey";

alter table "public"."PVPPlayers" add constraint "PVPPlayers_room_fkey" FOREIGN KEY (room) REFERENCES "PVPRooms"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."PVPPlayers" validate constraint "PVPPlayers_room_fkey";

alter table "public"."PVPRooms" add constraint "PVPRoom_host_fkey" FOREIGN KEY (host) REFERENCES players(uid) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."PVPRooms" validate constraint "PVPRoom_host_fkey";

grant delete on table "public"."PVPPlayers" to "anon";

grant insert on table "public"."PVPPlayers" to "anon";

grant references on table "public"."PVPPlayers" to "anon";

grant select on table "public"."PVPPlayers" to "anon";

grant trigger on table "public"."PVPPlayers" to "anon";

grant truncate on table "public"."PVPPlayers" to "anon";

grant update on table "public"."PVPPlayers" to "anon";

grant delete on table "public"."PVPPlayers" to "authenticated";

grant insert on table "public"."PVPPlayers" to "authenticated";

grant references on table "public"."PVPPlayers" to "authenticated";

grant select on table "public"."PVPPlayers" to "authenticated";

grant trigger on table "public"."PVPPlayers" to "authenticated";

grant truncate on table "public"."PVPPlayers" to "authenticated";

grant update on table "public"."PVPPlayers" to "authenticated";

grant delete on table "public"."PVPPlayers" to "service_role";

grant insert on table "public"."PVPPlayers" to "service_role";

grant references on table "public"."PVPPlayers" to "service_role";

grant select on table "public"."PVPPlayers" to "service_role";

grant trigger on table "public"."PVPPlayers" to "service_role";

grant truncate on table "public"."PVPPlayers" to "service_role";

grant update on table "public"."PVPPlayers" to "service_role";

grant delete on table "public"."PVPRooms" to "anon";

grant insert on table "public"."PVPRooms" to "anon";

grant references on table "public"."PVPRooms" to "anon";

grant select on table "public"."PVPRooms" to "anon";

grant trigger on table "public"."PVPRooms" to "anon";

grant truncate on table "public"."PVPRooms" to "anon";

grant update on table "public"."PVPRooms" to "anon";

grant delete on table "public"."PVPRooms" to "authenticated";

grant insert on table "public"."PVPRooms" to "authenticated";

grant references on table "public"."PVPRooms" to "authenticated";

grant select on table "public"."PVPRooms" to "authenticated";

grant trigger on table "public"."PVPRooms" to "authenticated";

grant truncate on table "public"."PVPRooms" to "authenticated";

grant update on table "public"."PVPRooms" to "authenticated";

grant delete on table "public"."PVPRooms" to "service_role";

grant insert on table "public"."PVPRooms" to "service_role";

grant references on table "public"."PVPRooms" to "service_role";

grant select on table "public"."PVPRooms" to "service_role";

grant trigger on table "public"."PVPRooms" to "service_role";

grant truncate on table "public"."PVPRooms" to "service_role";

grant update on table "public"."PVPRooms" to "service_role";


