create table "public"."clans" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "tag" text not null,
    "owner" uuid not null default gen_random_uuid()
);


alter table "public"."clans" enable row level security;

alter table "public"."players" add column "clan" bigint;

alter table "public"."players" add column "renameCooldown" timestamp with time zone not null default '2020-06-09 14:03:33.297+00'::timestamp with time zone;

CREATE UNIQUE INDEX clans_owner_key ON public.clans USING btree (owner);

CREATE UNIQUE INDEX clans_pkey ON public.clans USING btree (id);

CREATE UNIQUE INDEX clans_tag_key ON public.clans USING btree (tag);

alter table "public"."clans" add constraint "clans_pkey" PRIMARY KEY using index "clans_pkey";

alter table "public"."clans" add constraint "clans_owner_fkey" FOREIGN KEY (owner) REFERENCES players(uid) not valid;

alter table "public"."clans" validate constraint "clans_owner_fkey";

alter table "public"."clans" add constraint "clans_owner_key" UNIQUE using index "clans_owner_key";

alter table "public"."clans" add constraint "clans_tag_check" CHECK (((length(tag) <= 6) AND (length(tag) >= 3))) not valid;

alter table "public"."clans" validate constraint "clans_tag_check";

alter table "public"."clans" add constraint "clans_tag_key" UNIQUE using index "clans_tag_key";

alter table "public"."players" add constraint "players_clan_fkey" FOREIGN KEY (clan) REFERENCES clans(id) ON DELETE SET NULL not valid;

alter table "public"."players" validate constraint "players_clan_fkey";

grant delete on table "public"."clans" to "anon";

grant insert on table "public"."clans" to "anon";

grant references on table "public"."clans" to "anon";

grant select on table "public"."clans" to "anon";

grant trigger on table "public"."clans" to "anon";

grant truncate on table "public"."clans" to "anon";

grant update on table "public"."clans" to "anon";

grant delete on table "public"."clans" to "authenticated";

grant insert on table "public"."clans" to "authenticated";

grant references on table "public"."clans" to "authenticated";

grant select on table "public"."clans" to "authenticated";

grant trigger on table "public"."clans" to "authenticated";

grant truncate on table "public"."clans" to "authenticated";

grant update on table "public"."clans" to "authenticated";

grant delete on table "public"."clans" to "service_role";

grant insert on table "public"."clans" to "service_role";

grant references on table "public"."clans" to "service_role";

grant select on table "public"."clans" to "service_role";

grant trigger on table "public"."clans" to "service_role";

grant truncate on table "public"."clans" to "service_role";

grant update on table "public"."clans" to "service_role";


