revoke delete on table "public"."promotions" from "anon";

revoke insert on table "public"."promotions" from "anon";

revoke references on table "public"."promotions" from "anon";

revoke select on table "public"."promotions" from "anon";

revoke trigger on table "public"."promotions" from "anon";

revoke truncate on table "public"."promotions" from "anon";

revoke update on table "public"."promotions" from "anon";

revoke delete on table "public"."promotions" from "authenticated";

revoke insert on table "public"."promotions" from "authenticated";

revoke references on table "public"."promotions" from "authenticated";

revoke select on table "public"."promotions" from "authenticated";

revoke trigger on table "public"."promotions" from "authenticated";

revoke truncate on table "public"."promotions" from "authenticated";

revoke update on table "public"."promotions" from "authenticated";

revoke delete on table "public"."promotions" from "service_role";

revoke insert on table "public"."promotions" from "service_role";

revoke references on table "public"."promotions" from "service_role";

revoke select on table "public"."promotions" from "service_role";

revoke trigger on table "public"."promotions" from "service_role";

revoke truncate on table "public"."promotions" from "service_role";

revoke update on table "public"."promotions" from "service_role";

alter table "public"."promotions" drop constraint "promotions_pkey";

drop index if exists "public"."promotions_pkey";

drop table "public"."promotions";

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "start" timestamp with time zone not null,
    "end" timestamp with time zone not null,
    "title" text not null,
    "description" text not null,
    "imgUrl" text not null
);


alter table "public"."events" enable row level security;

CREATE UNIQUE INDEX promotions_pkey ON public.events USING btree (id);

alter table "public"."events" add constraint "promotions_pkey" PRIMARY KEY using index "promotions_pkey";

grant delete on table "public"."events" to "anon";

grant insert on table "public"."events" to "anon";

grant references on table "public"."events" to "anon";

grant select on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant update on table "public"."events" to "anon";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant references on table "public"."events" to "authenticated";

grant select on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";

grant delete on table "public"."events" to "service_role";

grant insert on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant select on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";

grant update on table "public"."events" to "service_role";


