create table "public"."clanInvitations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "to" uuid not null,
    "clan" bigint not null
);


alter table "public"."clanInvitations" enable row level security;

CREATE UNIQUE INDEX "clanInvitations_pkey" ON public."clanInvitations" USING btree (id);

alter table "public"."clanInvitations" add constraint "clanInvitations_pkey" PRIMARY KEY using index "clanInvitations_pkey";

alter table "public"."clanInvitations" add constraint "clanInvitations_clan_fkey" FOREIGN KEY (clan) REFERENCES clans(id) ON DELETE CASCADE not valid;

alter table "public"."clanInvitations" validate constraint "clanInvitations_clan_fkey";

alter table "public"."clanInvitations" add constraint "clanInvitations_to_fkey" FOREIGN KEY ("to") REFERENCES players(uid) ON DELETE CASCADE not valid;

alter table "public"."clanInvitations" validate constraint "clanInvitations_to_fkey";

grant delete on table "public"."clanInvitations" to "anon";

grant insert on table "public"."clanInvitations" to "anon";

grant references on table "public"."clanInvitations" to "anon";

grant select on table "public"."clanInvitations" to "anon";

grant trigger on table "public"."clanInvitations" to "anon";

grant truncate on table "public"."clanInvitations" to "anon";

grant update on table "public"."clanInvitations" to "anon";

grant delete on table "public"."clanInvitations" to "authenticated";

grant insert on table "public"."clanInvitations" to "authenticated";

grant references on table "public"."clanInvitations" to "authenticated";

grant select on table "public"."clanInvitations" to "authenticated";

grant trigger on table "public"."clanInvitations" to "authenticated";

grant truncate on table "public"."clanInvitations" to "authenticated";

grant update on table "public"."clanInvitations" to "authenticated";

grant delete on table "public"."clanInvitations" to "service_role";

grant insert on table "public"."clanInvitations" to "service_role";

grant references on table "public"."clanInvitations" to "service_role";

grant select on table "public"."clanInvitations" to "service_role";

grant trigger on table "public"."clanInvitations" to "service_role";

grant truncate on table "public"."clanInvitations" to "service_role";

grant update on table "public"."clanInvitations" to "service_role";


