create table "public"."deathCount" (
    "levelID" bigint generated by default as identity not null,
    "count" bigint[] not null,
    "uid" uuid not null
);


alter table "public"."deathCount" enable row level security;

CREATE UNIQUE INDEX "deathCount_pkey" ON public."deathCount" USING btree ("levelID", uid);

alter table "public"."deathCount" add constraint "deathCount_pkey" PRIMARY KEY using index "deathCount_pkey";

alter table "public"."deathCount" add constraint "deathCount_count_check" CHECK ((cardinality(count) = 100)) not valid;

alter table "public"."deathCount" validate constraint "deathCount_count_check";

alter table "public"."deathCount" add constraint "public_deathCount_uid_fkey" FOREIGN KEY (uid) REFERENCES players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."deathCount" validate constraint "public_deathCount_uid_fkey";

grant delete on table "public"."deathCount" to "anon";

grant insert on table "public"."deathCount" to "anon";

grant references on table "public"."deathCount" to "anon";

grant select on table "public"."deathCount" to "anon";

grant trigger on table "public"."deathCount" to "anon";

grant truncate on table "public"."deathCount" to "anon";

grant update on table "public"."deathCount" to "anon";

grant delete on table "public"."deathCount" to "authenticated";

grant insert on table "public"."deathCount" to "authenticated";

grant references on table "public"."deathCount" to "authenticated";

grant select on table "public"."deathCount" to "authenticated";

grant trigger on table "public"."deathCount" to "authenticated";

grant truncate on table "public"."deathCount" to "authenticated";

grant update on table "public"."deathCount" to "authenticated";

grant delete on table "public"."deathCount" to "service_role";

grant insert on table "public"."deathCount" to "service_role";

grant references on table "public"."deathCount" to "service_role";

grant select on table "public"."deathCount" to "service_role";

grant trigger on table "public"."deathCount" to "service_role";

grant truncate on table "public"."deathCount" to "service_role";

grant update on table "public"."deathCount" to "service_role";


