drop policy "Enable read access for all users" on "public"."achievement";

revoke delete on table "public"."achievement" from "anon";

revoke insert on table "public"."achievement" from "anon";

revoke references on table "public"."achievement" from "anon";

revoke select on table "public"."achievement" from "anon";

revoke trigger on table "public"."achievement" from "anon";

revoke truncate on table "public"."achievement" from "anon";

revoke update on table "public"."achievement" from "anon";

revoke delete on table "public"."achievement" from "authenticated";

revoke insert on table "public"."achievement" from "authenticated";

revoke references on table "public"."achievement" from "authenticated";

revoke select on table "public"."achievement" from "authenticated";

revoke trigger on table "public"."achievement" from "authenticated";

revoke truncate on table "public"."achievement" from "authenticated";

revoke update on table "public"."achievement" from "authenticated";

revoke delete on table "public"."achievement" from "service_role";

revoke insert on table "public"."achievement" from "service_role";

revoke references on table "public"."achievement" from "service_role";

revoke select on table "public"."achievement" from "service_role";

revoke trigger on table "public"."achievement" from "service_role";

revoke truncate on table "public"."achievement" from "service_role";

revoke update on table "public"."achievement" from "service_role";

alter table "public"."achievement" drop constraint "achievement_name_key";

alter table "public"."playersAchievement" drop constraint "playersAchievement_achievementid_fkey";

alter table "public"."achievement" drop constraint "achievement_pkey";

drop index if exists "public"."achievement_name_key";

drop index if exists "public"."achievement_pkey";

drop table "public"."achievement";

create table "public"."medals" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null default 'defaultname'::character varying
);


alter table "public"."medals" enable row level security;

create table "public"."playerMedal" (
    "userID" uuid not null,
    "medalID" bigint not null,
    "content" text
);


alter table "public"."playerMedal" enable row level security;

CREATE UNIQUE INDEX "playerMedal_pkey" ON public."playerMedal" USING btree ("userID", "medalID");

CREATE UNIQUE INDEX achievement_name_key ON public.medals USING btree (name);

CREATE UNIQUE INDEX achievement_pkey ON public.medals USING btree (id);

alter table "public"."medals" add constraint "achievement_pkey" PRIMARY KEY using index "achievement_pkey";

alter table "public"."playerMedal" add constraint "playerMedal_pkey" PRIMARY KEY using index "playerMedal_pkey";

alter table "public"."medals" add constraint "achievement_name_key" UNIQUE using index "achievement_name_key";

alter table "public"."playerMedal" add constraint "playerMedal_medalID_fkey" FOREIGN KEY ("medalID") REFERENCES medals(id) not valid;

alter table "public"."playerMedal" validate constraint "playerMedal_medalID_fkey";

alter table "public"."playerMedal" add constraint "playerMedal_userID_fkey" FOREIGN KEY ("userID") REFERENCES players(uid) not valid;

alter table "public"."playerMedal" validate constraint "playerMedal_userID_fkey";

alter table "public"."playersAchievement" add constraint "playersAchievement_achievementid_fkey" FOREIGN KEY (achievementid) REFERENCES medals(id) not valid;

alter table "public"."playersAchievement" validate constraint "playersAchievement_achievementid_fkey";

grant delete on table "public"."medals" to "anon";

grant insert on table "public"."medals" to "anon";

grant references on table "public"."medals" to "anon";

grant select on table "public"."medals" to "anon";

grant trigger on table "public"."medals" to "anon";

grant truncate on table "public"."medals" to "anon";

grant update on table "public"."medals" to "anon";

grant delete on table "public"."medals" to "authenticated";

grant insert on table "public"."medals" to "authenticated";

grant references on table "public"."medals" to "authenticated";

grant select on table "public"."medals" to "authenticated";

grant trigger on table "public"."medals" to "authenticated";

grant truncate on table "public"."medals" to "authenticated";

grant update on table "public"."medals" to "authenticated";

grant delete on table "public"."medals" to "service_role";

grant insert on table "public"."medals" to "service_role";

grant references on table "public"."medals" to "service_role";

grant select on table "public"."medals" to "service_role";

grant trigger on table "public"."medals" to "service_role";

grant truncate on table "public"."medals" to "service_role";

grant update on table "public"."medals" to "service_role";

grant delete on table "public"."playerMedal" to "anon";

grant insert on table "public"."playerMedal" to "anon";

grant references on table "public"."playerMedal" to "anon";

grant select on table "public"."playerMedal" to "anon";

grant trigger on table "public"."playerMedal" to "anon";

grant truncate on table "public"."playerMedal" to "anon";

grant update on table "public"."playerMedal" to "anon";

grant delete on table "public"."playerMedal" to "authenticated";

grant insert on table "public"."playerMedal" to "authenticated";

grant references on table "public"."playerMedal" to "authenticated";

grant select on table "public"."playerMedal" to "authenticated";

grant trigger on table "public"."playerMedal" to "authenticated";

grant truncate on table "public"."playerMedal" to "authenticated";

grant update on table "public"."playerMedal" to "authenticated";

grant delete on table "public"."playerMedal" to "service_role";

grant insert on table "public"."playerMedal" to "service_role";

grant references on table "public"."playerMedal" to "service_role";

grant select on table "public"."playerMedal" to "service_role";

grant trigger on table "public"."playerMedal" to "service_role";

grant truncate on table "public"."playerMedal" to "service_role";

grant update on table "public"."playerMedal" to "service_role";

create policy "Enable read access for all users"
on "public"."medals"
as permissive
for select
to public
using (true);



