alter table "public"."orderTracking" add column "link" text;

alter table "public"."orderTracking" alter column "id" add generated by default as identity;

alter table "public"."orders" add column "recipentName" text;


