alter table "public"."eventRecords" drop constraint "eventRecords_eventID_fkey";

alter table "public"."eventRecords" drop constraint "eventRecords_pkey";

drop index if exists "public"."eventRecords_pkey";

alter table "public"."eventLevels" add column "id" bigint generated by default as identity not null;

alter table "public"."eventRecords" drop column "eventID";

CREATE UNIQUE INDEX "eventLevels_id_key" ON public."eventLevels" USING btree (id);

alter table "public"."eventLevels" add constraint "eventLevels_id_key" UNIQUE using index "eventLevels_id_key";

alter table "public"."eventRecords" add constraint "eventRecords_levelID_fkey" FOREIGN KEY ("levelID") REFERENCES "eventLevels"(id) not valid;

alter table "public"."eventRecords" validate constraint "eventRecords_levelID_fkey";


