create table "public"."deliverySteps" (
    "created_at" timestamp with time zone not null default now(),
    "orderID" bigint not null,
    "id" bigint not null,
    "content" text
);


alter table "public"."deliverySteps" enable row level security;

create table "public"."orderItems" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userID" uuid not null,
    "productID" bigint not null,
    "orderID" bigint
);


alter table "public"."orderItems" enable row level security;

alter table "public"."orders" add column "paymentMethod" text not null default 'Bank Transfer'::text;

alter table "public"."orders" alter column "productID" drop not null;

alter table "public"."orders" alter column "quantity" drop not null;

alter table "public"."products" add column "description" text;

alter table "public"."products" add column "featured" boolean not null default false;

alter table "public"."products" add column "redirect" text;

CREATE UNIQUE INDEX "deliverySteps_pkey" ON public."deliverySteps" USING btree (id);

CREATE UNIQUE INDEX "orderItems_id_key" ON public."orderItems" USING btree (id);

CREATE UNIQUE INDEX "orderItems_pkey" ON public."orderItems" USING btree (id);

alter table "public"."deliverySteps" add constraint "deliverySteps_pkey" PRIMARY KEY using index "deliverySteps_pkey";

alter table "public"."orderItems" add constraint "orderItems_pkey" PRIMARY KEY using index "orderItems_pkey";

alter table "public"."deliverySteps" add constraint "deliverySteps_orderID_fkey" FOREIGN KEY ("orderID") REFERENCES orders(id) not valid;

alter table "public"."deliverySteps" validate constraint "deliverySteps_orderID_fkey";

alter table "public"."orderItems" add constraint "orderItems_id_key" UNIQUE using index "orderItems_id_key";

alter table "public"."orderItems" add constraint "orderItems_orderID_fkey" FOREIGN KEY ("orderID") REFERENCES orders(id) not valid;

alter table "public"."orderItems" validate constraint "orderItems_orderID_fkey";

alter table "public"."orderItems" add constraint "orderItems_productID_fkey" FOREIGN KEY ("productID") REFERENCES products(id) not valid;

alter table "public"."orderItems" validate constraint "orderItems_productID_fkey";

alter table "public"."orderItems" add constraint "orderItems_userID_fkey" FOREIGN KEY ("userID") REFERENCES players(uid) not valid;

alter table "public"."orderItems" validate constraint "orderItems_userID_fkey";

grant delete on table "public"."deliverySteps" to "anon";

grant insert on table "public"."deliverySteps" to "anon";

grant references on table "public"."deliverySteps" to "anon";

grant select on table "public"."deliverySteps" to "anon";

grant trigger on table "public"."deliverySteps" to "anon";

grant truncate on table "public"."deliverySteps" to "anon";

grant update on table "public"."deliverySteps" to "anon";

grant delete on table "public"."deliverySteps" to "authenticated";

grant insert on table "public"."deliverySteps" to "authenticated";

grant references on table "public"."deliverySteps" to "authenticated";

grant select on table "public"."deliverySteps" to "authenticated";

grant trigger on table "public"."deliverySteps" to "authenticated";

grant truncate on table "public"."deliverySteps" to "authenticated";

grant update on table "public"."deliverySteps" to "authenticated";

grant delete on table "public"."deliverySteps" to "service_role";

grant insert on table "public"."deliverySteps" to "service_role";

grant references on table "public"."deliverySteps" to "service_role";

grant select on table "public"."deliverySteps" to "service_role";

grant trigger on table "public"."deliverySteps" to "service_role";

grant truncate on table "public"."deliverySteps" to "service_role";

grant update on table "public"."deliverySteps" to "service_role";

grant delete on table "public"."orderItems" to "anon";

grant insert on table "public"."orderItems" to "anon";

grant references on table "public"."orderItems" to "anon";

grant select on table "public"."orderItems" to "anon";

grant trigger on table "public"."orderItems" to "anon";

grant truncate on table "public"."orderItems" to "anon";

grant update on table "public"."orderItems" to "anon";

grant delete on table "public"."orderItems" to "authenticated";

grant insert on table "public"."orderItems" to "authenticated";

grant references on table "public"."orderItems" to "authenticated";

grant select on table "public"."orderItems" to "authenticated";

grant trigger on table "public"."orderItems" to "authenticated";

grant truncate on table "public"."orderItems" to "authenticated";

grant update on table "public"."orderItems" to "authenticated";

grant delete on table "public"."orderItems" to "service_role";

grant insert on table "public"."orderItems" to "service_role";

grant references on table "public"."orderItems" to "service_role";

grant select on table "public"."orderItems" to "service_role";

grant trigger on table "public"."orderItems" to "service_role";

grant truncate on table "public"."orderItems" to "service_role";

grant update on table "public"."orderItems" to "service_role";


