CREATE TABLE IF NOT EXISTS "public"."listStars" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "listId" bigint NOT NULL,
    "uid" uuid NOT NULL
);


ALTER TABLE "public"."listStars" OWNER TO "postgres";


ALTER TABLE "public"."listStars" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listStars_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."listStars"
    ADD CONSTRAINT "listStars_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."listStars"
    ADD CONSTRAINT "list_stars_list_id_uid_key" UNIQUE ("listId", "uid");


CREATE INDEX IF NOT EXISTS "list_stars_list_id_idx" ON "public"."listStars" USING btree ("listId");
CREATE INDEX IF NOT EXISTS "list_stars_uid_idx" ON "public"."listStars" USING btree ("uid");


ALTER TABLE ONLY "public"."listStars"
    ADD CONSTRAINT "list_stars_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."listStars"
    ADD CONSTRAINT "list_stars_uid_fkey" FOREIGN KEY ("uid") REFERENCES "public"."players"("uid") ON DELETE CASCADE;