ALTER TABLE "public"."lists"
    ADD COLUMN IF NOT EXISTS "adminsCanManageHelpers" boolean DEFAULT false NOT NULL;

CREATE TABLE IF NOT EXISTS "public"."listMembers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "listId" bigint NOT NULL,
    "uid" uuid NOT NULL,
    "role" text NOT NULL,
    "addedBy" uuid NOT NULL,
    CONSTRAINT "list_members_role_check" CHECK (("role" = ANY (ARRAY['admin'::text, 'helper'::text]))),
    CONSTRAINT "list_members_list_id_uid_key" UNIQUE ("listId", "uid")
);

ALTER TABLE "public"."listMembers" OWNER TO "postgres";

ALTER TABLE ONLY "public"."listMembers"
    ADD CONSTRAINT "list_members_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."listMembers"
    ADD CONSTRAINT "list_members_uid_fkey" FOREIGN KEY ("uid") REFERENCES "public"."players"("uid") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."listMembers"
    ADD CONSTRAINT "list_members_added_by_fkey" FOREIGN KEY ("addedBy") REFERENCES "public"."players"("uid");

CREATE INDEX IF NOT EXISTS "list_members_list_id_idx" ON "public"."listMembers" ("listId");
CREATE INDEX IF NOT EXISTS "list_members_uid_idx" ON "public"."listMembers" ("uid");

CREATE TABLE IF NOT EXISTS "public"."listAuditLogs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "listId" bigint NOT NULL,
    "actorUid" uuid,
    "action" text NOT NULL,
    "targetUid" uuid,
    "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL
);

ALTER TABLE "public"."listAuditLogs" OWNER TO "postgres";

ALTER TABLE ONLY "public"."listAuditLogs"
    ADD CONSTRAINT "list_audit_logs_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."listAuditLogs"
    ADD CONSTRAINT "list_audit_logs_actor_uid_fkey" FOREIGN KEY ("actorUid") REFERENCES "public"."players"("uid") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."listAuditLogs"
    ADD CONSTRAINT "list_audit_logs_target_uid_fkey" FOREIGN KEY ("targetUid") REFERENCES "public"."players"("uid") ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "list_audit_logs_list_id_created_at_idx" ON "public"."listAuditLogs" ("listId", "created_at" DESC);