CREATE TABLE IF NOT EXISTS "public"."listInvitations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "listId" bigint NOT NULL,
    "uid" uuid NOT NULL,
    "role" text NOT NULL,
    "invitedBy" uuid NOT NULL,
    CONSTRAINT "list_invitations_role_check" CHECK (("role" = ANY (ARRAY['admin'::text, 'helper'::text])))
);

ALTER TABLE ONLY "public"."listInvitations"
    ADD CONSTRAINT "listInvitations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."listInvitations"
    ADD CONSTRAINT "list_invitations_list_id_uid_key" UNIQUE ("listId", "uid");

CREATE INDEX "list_invitations_list_id_idx" ON "public"."listInvitations" USING btree ("listId");

CREATE INDEX "list_invitations_uid_idx" ON "public"."listInvitations" USING btree ("uid");

ALTER TABLE ONLY "public"."listInvitations"
    ADD CONSTRAINT "list_invitations_invited_by_fkey" FOREIGN KEY ("invitedBy") REFERENCES "public"."players"("uid");

ALTER TABLE ONLY "public"."listInvitations"
    ADD CONSTRAINT "list_invitations_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."listInvitations"
    ADD CONSTRAINT "list_invitations_uid_fkey" FOREIGN KEY ("uid") REFERENCES "public"."players"("uid") ON DELETE CASCADE;