CREATE TABLE IF NOT EXISTS "public"."listLeaderboardRefreshes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "listId" bigint NOT NULL,
    "totalPlayers" bigint DEFAULT '0'::bigint NOT NULL,
    "lastRefreshedAt" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."listLeaderboardRefreshes" OWNER TO "postgres";


ALTER TABLE "public"."listLeaderboardRefreshes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listLeaderboardRefreshes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."listLeaderboardEntries" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "refreshId" bigint NOT NULL,
    "uid" "uuid" NOT NULL,
    "rank" bigint NOT NULL,
    "score" double precision NOT NULL,
    "completedCount" integer DEFAULT 0 NOT NULL,
    CONSTRAINT "listLeaderboardEntries_completedCount_check" CHECK (("completedCount" >= 0)),
    CONSTRAINT "listLeaderboardEntries_rank_check" CHECK (("rank" > 0))
);


ALTER TABLE "public"."listLeaderboardEntries" OWNER TO "postgres";


ALTER TABLE "public"."listLeaderboardEntries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listLeaderboardEntries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."listLeaderboardRefreshes"
    ADD CONSTRAINT "listLeaderboardRefreshes_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "listLeaderboardEntries_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "list_leaderboard_entries_refresh_id_rank_key" UNIQUE ("refreshId", "rank");


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "list_leaderboard_entries_refresh_id_uid_key" UNIQUE ("refreshId", "uid");


ALTER TABLE ONLY "public"."listLeaderboardRefreshes"
    ADD CONSTRAINT "list_leaderboard_refreshes_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "list_leaderboard_entries_refresh_id_fkey" FOREIGN KEY ("refreshId") REFERENCES "public"."listLeaderboardRefreshes"("id") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "list_leaderboard_entries_uid_fkey" FOREIGN KEY ("uid") REFERENCES "public"."players"("uid") ON DELETE CASCADE;


CREATE INDEX "list_leaderboard_entries_refresh_id_rank_idx" ON "public"."listLeaderboardEntries" USING "btree" ("refreshId", "rank");


CREATE INDEX "list_leaderboard_refreshes_list_id_last_refreshed_at_idx" ON "public"."listLeaderboardRefreshes" USING "btree" ("listId", "lastRefreshedAt" DESC);