
  create table "public"."battlePassXPLogs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userID" uuid not null,
    "seasonId" bigint not null,
    "amount" bigint not null,
    "source" text not null,
    "refId" bigint,
    "description" text
      );


alter table "public"."battlePassXPLogs" enable row level security;

alter table "public"."battlePassMissions" add column "refreshType" text not null default 'none'::text;

CREATE UNIQUE INDEX "battlePassXPLogs_pkey" ON public."battlePassXPLogs" USING btree (id);

CREATE INDEX "battlePassXPLogs_seasonId_idx" ON public."battlePassXPLogs" USING btree ("seasonId");

CREATE INDEX "battlePassXPLogs_source_refId_idx" ON public."battlePassXPLogs" USING btree (source, "refId");

CREATE INDEX "battlePassXPLogs_userID_idx" ON public."battlePassXPLogs" USING btree ("userID");

alter table "public"."battlePassXPLogs" add constraint "battlePassXPLogs_pkey" PRIMARY KEY using index "battlePassXPLogs_pkey";

alter table "public"."battlePassXPLogs" add constraint "battlePassXPLogs_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES public."battlePassSeasons"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassXPLogs" validate constraint "battlePassXPLogs_seasonId_fkey";

alter table "public"."battlePassXPLogs" add constraint "battlePassXPLogs_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassXPLogs" validate constraint "battlePassXPLogs_userID_fkey";

grant delete on table "public"."battlePassXPLogs" to "anon";

grant insert on table "public"."battlePassXPLogs" to "anon";

grant references on table "public"."battlePassXPLogs" to "anon";

grant select on table "public"."battlePassXPLogs" to "anon";

grant trigger on table "public"."battlePassXPLogs" to "anon";

grant truncate on table "public"."battlePassXPLogs" to "anon";

grant update on table "public"."battlePassXPLogs" to "anon";

grant delete on table "public"."battlePassXPLogs" to "authenticated";

grant insert on table "public"."battlePassXPLogs" to "authenticated";

grant references on table "public"."battlePassXPLogs" to "authenticated";

grant select on table "public"."battlePassXPLogs" to "authenticated";

grant trigger on table "public"."battlePassXPLogs" to "authenticated";

grant truncate on table "public"."battlePassXPLogs" to "authenticated";

grant update on table "public"."battlePassXPLogs" to "authenticated";

grant delete on table "public"."battlePassXPLogs" to "service_role";

grant insert on table "public"."battlePassXPLogs" to "service_role";

grant references on table "public"."battlePassXPLogs" to "service_role";

grant select on table "public"."battlePassXPLogs" to "service_role";

grant trigger on table "public"."battlePassXPLogs" to "service_role";

grant truncate on table "public"."battlePassXPLogs" to "service_role";

grant update on table "public"."battlePassXPLogs" to "service_role";


