alter table "public"."subscriptions" drop constraint "subscriptions_userID_fkey";

alter table "public"."subscriptions" drop constraint "subscriptions_pkey";

drop index if exists "public"."subscriptions_pkey";


  create table "public"."battlePassLevelProgress" (
    "created_at" timestamp with time zone not null default now(),
    "battlePassLevelId" bigint not null,
    "userID" uuid not null,
    "progress" bigint not null default '0'::bigint,
    "minProgressClaimed" boolean not null default false,
    "completionClaimed" boolean not null default false
      );


alter table "public"."battlePassLevelProgress" enable row level security;


  create table "public"."battlePassLevels" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "seasonId" bigint not null,
    "levelID" bigint not null,
    "xp" bigint not null default '1000'::bigint,
    "minProgressXp" bigint not null default '500'::bigint,
    "minProgress" bigint not null default '50'::bigint
      );


alter table "public"."battlePassLevels" enable row level security;


  create table "public"."battlePassMapPackProgress" (
    "created_at" timestamp with time zone not null default now(),
    "battlePassMapPackId" bigint not null,
    "userID" uuid not null,
    "completedLevels" bigint[] not null default '{}'::bigint[],
    "claimed" boolean not null default false
      );


alter table "public"."battlePassMapPackProgress" enable row level security;


  create table "public"."battlePassMapPacks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "seasonId" bigint not null,
    "mapPackId" bigint not null,
    "unlockWeek" bigint not null,
    "order" bigint not null default '0'::bigint
      );


alter table "public"."battlePassMapPacks" enable row level security;


  create table "public"."battlePassMissionClaims" (
    "created_at" timestamp with time zone not null default now(),
    "missionId" bigint not null,
    "userID" uuid not null
      );


alter table "public"."battlePassMissionClaims" enable row level security;


  create table "public"."battlePassMissionProgress" (
    "created_at" timestamp with time zone not null default now(),
    "missionId" bigint not null,
    "userID" uuid not null,
    "completed" boolean not null default false
      );


alter table "public"."battlePassMissionProgress" enable row level security;


  create table "public"."battlePassMissionRewards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "missionId" bigint not null,
    "itemId" bigint not null,
    "quantity" bigint not null default '1'::bigint,
    "expireAfter" bigint
      );


alter table "public"."battlePassMissionRewards" enable row level security;


  create table "public"."battlePassMissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "seasonId" bigint not null,
    "title" text not null,
    "description" text,
    "condition" jsonb not null,
    "xp" bigint not null,
    "order" bigint not null default '0'::bigint
      );


alter table "public"."battlePassMissions" enable row level security;


  create table "public"."battlePassProgress" (
    "created_at" timestamp with time zone not null default now(),
    "seasonId" bigint not null,
    "userID" uuid not null,
    "xp" bigint not null default '0'::bigint
      );


alter table "public"."battlePassProgress" enable row level security;


  create table "public"."battlePassRewardClaims" (
    "created_at" timestamp with time zone not null default now(),
    "rewardId" bigint not null,
    "userID" uuid not null
      );


alter table "public"."battlePassRewardClaims" enable row level security;


  create table "public"."battlePassSeasons" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text,
    "start" timestamp with time zone not null,
    "end" timestamp with time zone not null,
    "isArchived" boolean not null default false,
    "premiumPrice" bigint not null default '149000'::bigint,
    "primaryColor" text
      );


alter table "public"."battlePassSeasons" enable row level security;


  create table "public"."battlePassTierRewards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "seasonId" bigint not null,
    "tier" bigint not null,
    "isPremium" boolean not null default false,
    "itemId" bigint not null,
    "quantity" bigint not null default '1'::bigint,
    "description" text
      );


alter table "public"."battlePassTierRewards" enable row level security;


  create table "public"."mapPackLevels" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "mapPackId" bigint not null,
    "levelID" bigint not null,
    "order" bigint not null default '0'::bigint
      );


alter table "public"."mapPackLevels" enable row level security;


  create table "public"."mapPacks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "difficulty" text not null,
    "xp" bigint not null
      );


alter table "public"."mapPacks" enable row level security;


  create table "public"."playerSubscriptions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "userID" uuid not null,
    "subscriptionId" bigint not null,
    "refId" bigint,
    "start" timestamp with time zone not null default now(),
    "end" timestamp with time zone
      );


alter table "public"."playerSubscriptions" enable row level security;

alter table "public"."subscriptions" drop column "expireAt";

alter table "public"."subscriptions" drop column "userID";

alter table "public"."subscriptions" add column "description" text;

alter table "public"."subscriptions" add column "id" bigint generated by default as identity not null;

alter table "public"."subscriptions" add column "name" text not null;

alter table "public"."subscriptions" add column "price" bigint not null;

CREATE UNIQUE INDEX "battlePassLevelProgress_pkey" ON public."battlePassLevelProgress" USING btree ("battlePassLevelId", "userID");

CREATE UNIQUE INDEX "battlePassLevels_pkey" ON public."battlePassLevels" USING btree (id);

CREATE UNIQUE INDEX "battlePassMapPackProgress_pkey" ON public."battlePassMapPackProgress" USING btree ("battlePassMapPackId", "userID");

CREATE UNIQUE INDEX "battlePassMapPacks_pkey" ON public."battlePassMapPacks" USING btree (id);

CREATE UNIQUE INDEX "battlePassMissionClaims_pkey" ON public."battlePassMissionClaims" USING btree ("missionId", "userID");

CREATE UNIQUE INDEX "battlePassMissionProgress_pkey" ON public."battlePassMissionProgress" USING btree ("missionId", "userID");

CREATE UNIQUE INDEX "battlePassMissionRewards_pkey" ON public."battlePassMissionRewards" USING btree (id);

CREATE UNIQUE INDEX "battlePassMissions_pkey" ON public."battlePassMissions" USING btree (id);

CREATE UNIQUE INDEX "battlePassProgress_pkey" ON public."battlePassProgress" USING btree ("seasonId", "userID");

CREATE UNIQUE INDEX "battlePassRewardClaims_pkey" ON public."battlePassRewardClaims" USING btree ("rewardId", "userID");

CREATE UNIQUE INDEX "battlePassSeasons_pkey" ON public."battlePassSeasons" USING btree (id);

CREATE UNIQUE INDEX "battlePassTierRewards_pkey" ON public."battlePassTierRewards" USING btree (id);

CREATE UNIQUE INDEX "mapPackLevels_pkey" ON public."mapPackLevels" USING btree (id);

CREATE UNIQUE INDEX "mapPacks_pkey" ON public."mapPacks" USING btree (id);

CREATE UNIQUE INDEX "playerSubscriptions_pkey" ON public."playerSubscriptions" USING btree (id);

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

alter table "public"."battlePassLevelProgress" add constraint "battlePassLevelProgress_pkey" PRIMARY KEY using index "battlePassLevelProgress_pkey";

alter table "public"."battlePassLevels" add constraint "battlePassLevels_pkey" PRIMARY KEY using index "battlePassLevels_pkey";

alter table "public"."battlePassMapPackProgress" add constraint "battlePassMapPackProgress_pkey" PRIMARY KEY using index "battlePassMapPackProgress_pkey";

alter table "public"."battlePassMapPacks" add constraint "battlePassMapPacks_pkey" PRIMARY KEY using index "battlePassMapPacks_pkey";

alter table "public"."battlePassMissionClaims" add constraint "battlePassMissionClaims_pkey" PRIMARY KEY using index "battlePassMissionClaims_pkey";

alter table "public"."battlePassMissionProgress" add constraint "battlePassMissionProgress_pkey" PRIMARY KEY using index "battlePassMissionProgress_pkey";

alter table "public"."battlePassMissionRewards" add constraint "battlePassMissionRewards_pkey" PRIMARY KEY using index "battlePassMissionRewards_pkey";

alter table "public"."battlePassMissions" add constraint "battlePassMissions_pkey" PRIMARY KEY using index "battlePassMissions_pkey";

alter table "public"."battlePassProgress" add constraint "battlePassProgress_pkey" PRIMARY KEY using index "battlePassProgress_pkey";

alter table "public"."battlePassRewardClaims" add constraint "battlePassRewardClaims_pkey" PRIMARY KEY using index "battlePassRewardClaims_pkey";

alter table "public"."battlePassSeasons" add constraint "battlePassSeasons_pkey" PRIMARY KEY using index "battlePassSeasons_pkey";

alter table "public"."battlePassTierRewards" add constraint "battlePassTierRewards_pkey" PRIMARY KEY using index "battlePassTierRewards_pkey";

alter table "public"."mapPackLevels" add constraint "mapPackLevels_pkey" PRIMARY KEY using index "mapPackLevels_pkey";

alter table "public"."mapPacks" add constraint "mapPacks_pkey" PRIMARY KEY using index "mapPacks_pkey";

alter table "public"."playerSubscriptions" add constraint "playerSubscriptions_pkey" PRIMARY KEY using index "playerSubscriptions_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."battlePassLevelProgress" add constraint "battlePassLevelProgress_battlePassLevelId_fkey" FOREIGN KEY ("battlePassLevelId") REFERENCES public."battlePassLevels"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassLevelProgress" validate constraint "battlePassLevelProgress_battlePassLevelId_fkey";

alter table "public"."battlePassLevelProgress" add constraint "battlePassLevelProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassLevelProgress" validate constraint "battlePassLevelProgress_userID_fkey";

alter table "public"."battlePassLevels" add constraint "battlePassLevels_levelID_fkey" FOREIGN KEY ("levelID") REFERENCES public.levels(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassLevels" validate constraint "battlePassLevels_levelID_fkey";

alter table "public"."battlePassLevels" add constraint "battlePassLevels_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES public."battlePassSeasons"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassLevels" validate constraint "battlePassLevels_seasonId_fkey";

alter table "public"."battlePassMapPackProgress" add constraint "battlePassMapPackProgress_battlePassMapPackId_fkey" FOREIGN KEY ("battlePassMapPackId") REFERENCES public."battlePassMapPacks"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMapPackProgress" validate constraint "battlePassMapPackProgress_battlePassMapPackId_fkey";

alter table "public"."battlePassMapPackProgress" add constraint "battlePassMapPackProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMapPackProgress" validate constraint "battlePassMapPackProgress_userID_fkey";

alter table "public"."battlePassMapPacks" add constraint "battlePassMapPacks_mapPackId_fkey" FOREIGN KEY ("mapPackId") REFERENCES public."mapPacks"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMapPacks" validate constraint "battlePassMapPacks_mapPackId_fkey";

alter table "public"."battlePassMapPacks" add constraint "battlePassMapPacks_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES public."battlePassSeasons"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMapPacks" validate constraint "battlePassMapPacks_seasonId_fkey";

alter table "public"."battlePassMissionClaims" add constraint "battlePassMissionClaims_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES public."battlePassMissions"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMissionClaims" validate constraint "battlePassMissionClaims_missionId_fkey";

alter table "public"."battlePassMissionClaims" add constraint "battlePassMissionClaims_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMissionClaims" validate constraint "battlePassMissionClaims_userID_fkey";

alter table "public"."battlePassMissionProgress" add constraint "battlePassMissionProgress_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES public."battlePassMissions"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMissionProgress" validate constraint "battlePassMissionProgress_missionId_fkey";

alter table "public"."battlePassMissionProgress" add constraint "battlePassMissionProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMissionProgress" validate constraint "battlePassMissionProgress_userID_fkey";

alter table "public"."battlePassMissionRewards" add constraint "battlePassMissionRewards_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES public.items(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMissionRewards" validate constraint "battlePassMissionRewards_itemId_fkey";

alter table "public"."battlePassMissionRewards" add constraint "battlePassMissionRewards_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES public."battlePassMissions"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMissionRewards" validate constraint "battlePassMissionRewards_missionId_fkey";

alter table "public"."battlePassMissions" add constraint "battlePassMissions_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES public."battlePassSeasons"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassMissions" validate constraint "battlePassMissions_seasonId_fkey";

alter table "public"."battlePassProgress" add constraint "battlePassProgress_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES public."battlePassSeasons"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassProgress" validate constraint "battlePassProgress_seasonId_fkey";

alter table "public"."battlePassProgress" add constraint "battlePassProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassProgress" validate constraint "battlePassProgress_userID_fkey";

alter table "public"."battlePassRewardClaims" add constraint "battlePassRewardClaims_rewardId_fkey" FOREIGN KEY ("rewardId") REFERENCES public."battlePassTierRewards"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassRewardClaims" validate constraint "battlePassRewardClaims_rewardId_fkey";

alter table "public"."battlePassRewardClaims" add constraint "battlePassRewardClaims_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassRewardClaims" validate constraint "battlePassRewardClaims_userID_fkey";

alter table "public"."battlePassTierRewards" add constraint "battlePassTierRewards_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES public.items(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassTierRewards" validate constraint "battlePassTierRewards_itemId_fkey";

alter table "public"."battlePassTierRewards" add constraint "battlePassTierRewards_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES public."battlePassSeasons"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."battlePassTierRewards" validate constraint "battlePassTierRewards_seasonId_fkey";

alter table "public"."mapPackLevels" add constraint "mapPackLevels_levelID_fkey" FOREIGN KEY ("levelID") REFERENCES public.levels(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."mapPackLevels" validate constraint "mapPackLevels_levelID_fkey";

alter table "public"."mapPackLevels" add constraint "mapPackLevels_mapPackId_fkey" FOREIGN KEY ("mapPackId") REFERENCES public."mapPacks"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."mapPackLevels" validate constraint "mapPackLevels_mapPackId_fkey";

alter table "public"."mapPacks" add constraint "mapPacks_difficulty_check" CHECK ((difficulty = ANY (ARRAY['easier'::text, 'harder'::text, 'medium_demon'::text, 'insane_demon'::text]))) not valid;

alter table "public"."mapPacks" validate constraint "mapPacks_difficulty_check";

alter table "public"."playerSubscriptions" add constraint "playerSubscriptions_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES public.subscriptions(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."playerSubscriptions" validate constraint "playerSubscriptions_subscriptionId_fkey";

alter table "public"."playerSubscriptions" add constraint "playerSubscriptions_userID_fkey" FOREIGN KEY ("userID") REFERENCES public.players(uid) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."playerSubscriptions" validate constraint "playerSubscriptions_userID_fkey";

grant delete on table "public"."battlePassLevelProgress" to "anon";

grant insert on table "public"."battlePassLevelProgress" to "anon";

grant references on table "public"."battlePassLevelProgress" to "anon";

grant select on table "public"."battlePassLevelProgress" to "anon";

grant trigger on table "public"."battlePassLevelProgress" to "anon";

grant truncate on table "public"."battlePassLevelProgress" to "anon";

grant update on table "public"."battlePassLevelProgress" to "anon";

grant delete on table "public"."battlePassLevelProgress" to "authenticated";

grant insert on table "public"."battlePassLevelProgress" to "authenticated";

grant references on table "public"."battlePassLevelProgress" to "authenticated";

grant select on table "public"."battlePassLevelProgress" to "authenticated";

grant trigger on table "public"."battlePassLevelProgress" to "authenticated";

grant truncate on table "public"."battlePassLevelProgress" to "authenticated";

grant update on table "public"."battlePassLevelProgress" to "authenticated";

grant delete on table "public"."battlePassLevelProgress" to "service_role";

grant insert on table "public"."battlePassLevelProgress" to "service_role";

grant references on table "public"."battlePassLevelProgress" to "service_role";

grant select on table "public"."battlePassLevelProgress" to "service_role";

grant trigger on table "public"."battlePassLevelProgress" to "service_role";

grant truncate on table "public"."battlePassLevelProgress" to "service_role";

grant update on table "public"."battlePassLevelProgress" to "service_role";

grant delete on table "public"."battlePassLevels" to "anon";

grant insert on table "public"."battlePassLevels" to "anon";

grant references on table "public"."battlePassLevels" to "anon";

grant select on table "public"."battlePassLevels" to "anon";

grant trigger on table "public"."battlePassLevels" to "anon";

grant truncate on table "public"."battlePassLevels" to "anon";

grant update on table "public"."battlePassLevels" to "anon";

grant delete on table "public"."battlePassLevels" to "authenticated";

grant insert on table "public"."battlePassLevels" to "authenticated";

grant references on table "public"."battlePassLevels" to "authenticated";

grant select on table "public"."battlePassLevels" to "authenticated";

grant trigger on table "public"."battlePassLevels" to "authenticated";

grant truncate on table "public"."battlePassLevels" to "authenticated";

grant update on table "public"."battlePassLevels" to "authenticated";

grant delete on table "public"."battlePassLevels" to "service_role";

grant insert on table "public"."battlePassLevels" to "service_role";

grant references on table "public"."battlePassLevels" to "service_role";

grant select on table "public"."battlePassLevels" to "service_role";

grant trigger on table "public"."battlePassLevels" to "service_role";

grant truncate on table "public"."battlePassLevels" to "service_role";

grant update on table "public"."battlePassLevels" to "service_role";

grant delete on table "public"."battlePassMapPackProgress" to "anon";

grant insert on table "public"."battlePassMapPackProgress" to "anon";

grant references on table "public"."battlePassMapPackProgress" to "anon";

grant select on table "public"."battlePassMapPackProgress" to "anon";

grant trigger on table "public"."battlePassMapPackProgress" to "anon";

grant truncate on table "public"."battlePassMapPackProgress" to "anon";

grant update on table "public"."battlePassMapPackProgress" to "anon";

grant delete on table "public"."battlePassMapPackProgress" to "authenticated";

grant insert on table "public"."battlePassMapPackProgress" to "authenticated";

grant references on table "public"."battlePassMapPackProgress" to "authenticated";

grant select on table "public"."battlePassMapPackProgress" to "authenticated";

grant trigger on table "public"."battlePassMapPackProgress" to "authenticated";

grant truncate on table "public"."battlePassMapPackProgress" to "authenticated";

grant update on table "public"."battlePassMapPackProgress" to "authenticated";

grant delete on table "public"."battlePassMapPackProgress" to "service_role";

grant insert on table "public"."battlePassMapPackProgress" to "service_role";

grant references on table "public"."battlePassMapPackProgress" to "service_role";

grant select on table "public"."battlePassMapPackProgress" to "service_role";

grant trigger on table "public"."battlePassMapPackProgress" to "service_role";

grant truncate on table "public"."battlePassMapPackProgress" to "service_role";

grant update on table "public"."battlePassMapPackProgress" to "service_role";

grant delete on table "public"."battlePassMapPacks" to "anon";

grant insert on table "public"."battlePassMapPacks" to "anon";

grant references on table "public"."battlePassMapPacks" to "anon";

grant select on table "public"."battlePassMapPacks" to "anon";

grant trigger on table "public"."battlePassMapPacks" to "anon";

grant truncate on table "public"."battlePassMapPacks" to "anon";

grant update on table "public"."battlePassMapPacks" to "anon";

grant delete on table "public"."battlePassMapPacks" to "authenticated";

grant insert on table "public"."battlePassMapPacks" to "authenticated";

grant references on table "public"."battlePassMapPacks" to "authenticated";

grant select on table "public"."battlePassMapPacks" to "authenticated";

grant trigger on table "public"."battlePassMapPacks" to "authenticated";

grant truncate on table "public"."battlePassMapPacks" to "authenticated";

grant update on table "public"."battlePassMapPacks" to "authenticated";

grant delete on table "public"."battlePassMapPacks" to "service_role";

grant insert on table "public"."battlePassMapPacks" to "service_role";

grant references on table "public"."battlePassMapPacks" to "service_role";

grant select on table "public"."battlePassMapPacks" to "service_role";

grant trigger on table "public"."battlePassMapPacks" to "service_role";

grant truncate on table "public"."battlePassMapPacks" to "service_role";

grant update on table "public"."battlePassMapPacks" to "service_role";

grant delete on table "public"."battlePassMissionClaims" to "anon";

grant insert on table "public"."battlePassMissionClaims" to "anon";

grant references on table "public"."battlePassMissionClaims" to "anon";

grant select on table "public"."battlePassMissionClaims" to "anon";

grant trigger on table "public"."battlePassMissionClaims" to "anon";

grant truncate on table "public"."battlePassMissionClaims" to "anon";

grant update on table "public"."battlePassMissionClaims" to "anon";

grant delete on table "public"."battlePassMissionClaims" to "authenticated";

grant insert on table "public"."battlePassMissionClaims" to "authenticated";

grant references on table "public"."battlePassMissionClaims" to "authenticated";

grant select on table "public"."battlePassMissionClaims" to "authenticated";

grant trigger on table "public"."battlePassMissionClaims" to "authenticated";

grant truncate on table "public"."battlePassMissionClaims" to "authenticated";

grant update on table "public"."battlePassMissionClaims" to "authenticated";

grant delete on table "public"."battlePassMissionClaims" to "service_role";

grant insert on table "public"."battlePassMissionClaims" to "service_role";

grant references on table "public"."battlePassMissionClaims" to "service_role";

grant select on table "public"."battlePassMissionClaims" to "service_role";

grant trigger on table "public"."battlePassMissionClaims" to "service_role";

grant truncate on table "public"."battlePassMissionClaims" to "service_role";

grant update on table "public"."battlePassMissionClaims" to "service_role";

grant delete on table "public"."battlePassMissionProgress" to "anon";

grant insert on table "public"."battlePassMissionProgress" to "anon";

grant references on table "public"."battlePassMissionProgress" to "anon";

grant select on table "public"."battlePassMissionProgress" to "anon";

grant trigger on table "public"."battlePassMissionProgress" to "anon";

grant truncate on table "public"."battlePassMissionProgress" to "anon";

grant update on table "public"."battlePassMissionProgress" to "anon";

grant delete on table "public"."battlePassMissionProgress" to "authenticated";

grant insert on table "public"."battlePassMissionProgress" to "authenticated";

grant references on table "public"."battlePassMissionProgress" to "authenticated";

grant select on table "public"."battlePassMissionProgress" to "authenticated";

grant trigger on table "public"."battlePassMissionProgress" to "authenticated";

grant truncate on table "public"."battlePassMissionProgress" to "authenticated";

grant update on table "public"."battlePassMissionProgress" to "authenticated";

grant delete on table "public"."battlePassMissionProgress" to "service_role";

grant insert on table "public"."battlePassMissionProgress" to "service_role";

grant references on table "public"."battlePassMissionProgress" to "service_role";

grant select on table "public"."battlePassMissionProgress" to "service_role";

grant trigger on table "public"."battlePassMissionProgress" to "service_role";

grant truncate on table "public"."battlePassMissionProgress" to "service_role";

grant update on table "public"."battlePassMissionProgress" to "service_role";

grant delete on table "public"."battlePassMissionRewards" to "anon";

grant insert on table "public"."battlePassMissionRewards" to "anon";

grant references on table "public"."battlePassMissionRewards" to "anon";

grant select on table "public"."battlePassMissionRewards" to "anon";

grant trigger on table "public"."battlePassMissionRewards" to "anon";

grant truncate on table "public"."battlePassMissionRewards" to "anon";

grant update on table "public"."battlePassMissionRewards" to "anon";

grant delete on table "public"."battlePassMissionRewards" to "authenticated";

grant insert on table "public"."battlePassMissionRewards" to "authenticated";

grant references on table "public"."battlePassMissionRewards" to "authenticated";

grant select on table "public"."battlePassMissionRewards" to "authenticated";

grant trigger on table "public"."battlePassMissionRewards" to "authenticated";

grant truncate on table "public"."battlePassMissionRewards" to "authenticated";

grant update on table "public"."battlePassMissionRewards" to "authenticated";

grant delete on table "public"."battlePassMissionRewards" to "service_role";

grant insert on table "public"."battlePassMissionRewards" to "service_role";

grant references on table "public"."battlePassMissionRewards" to "service_role";

grant select on table "public"."battlePassMissionRewards" to "service_role";

grant trigger on table "public"."battlePassMissionRewards" to "service_role";

grant truncate on table "public"."battlePassMissionRewards" to "service_role";

grant update on table "public"."battlePassMissionRewards" to "service_role";

grant delete on table "public"."battlePassMissions" to "anon";

grant insert on table "public"."battlePassMissions" to "anon";

grant references on table "public"."battlePassMissions" to "anon";

grant select on table "public"."battlePassMissions" to "anon";

grant trigger on table "public"."battlePassMissions" to "anon";

grant truncate on table "public"."battlePassMissions" to "anon";

grant update on table "public"."battlePassMissions" to "anon";

grant delete on table "public"."battlePassMissions" to "authenticated";

grant insert on table "public"."battlePassMissions" to "authenticated";

grant references on table "public"."battlePassMissions" to "authenticated";

grant select on table "public"."battlePassMissions" to "authenticated";

grant trigger on table "public"."battlePassMissions" to "authenticated";

grant truncate on table "public"."battlePassMissions" to "authenticated";

grant update on table "public"."battlePassMissions" to "authenticated";

grant delete on table "public"."battlePassMissions" to "service_role";

grant insert on table "public"."battlePassMissions" to "service_role";

grant references on table "public"."battlePassMissions" to "service_role";

grant select on table "public"."battlePassMissions" to "service_role";

grant trigger on table "public"."battlePassMissions" to "service_role";

grant truncate on table "public"."battlePassMissions" to "service_role";

grant update on table "public"."battlePassMissions" to "service_role";

grant delete on table "public"."battlePassProgress" to "anon";

grant insert on table "public"."battlePassProgress" to "anon";

grant references on table "public"."battlePassProgress" to "anon";

grant select on table "public"."battlePassProgress" to "anon";

grant trigger on table "public"."battlePassProgress" to "anon";

grant truncate on table "public"."battlePassProgress" to "anon";

grant update on table "public"."battlePassProgress" to "anon";

grant delete on table "public"."battlePassProgress" to "authenticated";

grant insert on table "public"."battlePassProgress" to "authenticated";

grant references on table "public"."battlePassProgress" to "authenticated";

grant select on table "public"."battlePassProgress" to "authenticated";

grant trigger on table "public"."battlePassProgress" to "authenticated";

grant truncate on table "public"."battlePassProgress" to "authenticated";

grant update on table "public"."battlePassProgress" to "authenticated";

grant delete on table "public"."battlePassProgress" to "service_role";

grant insert on table "public"."battlePassProgress" to "service_role";

grant references on table "public"."battlePassProgress" to "service_role";

grant select on table "public"."battlePassProgress" to "service_role";

grant trigger on table "public"."battlePassProgress" to "service_role";

grant truncate on table "public"."battlePassProgress" to "service_role";

grant update on table "public"."battlePassProgress" to "service_role";

grant delete on table "public"."battlePassRewardClaims" to "anon";

grant insert on table "public"."battlePassRewardClaims" to "anon";

grant references on table "public"."battlePassRewardClaims" to "anon";

grant select on table "public"."battlePassRewardClaims" to "anon";

grant trigger on table "public"."battlePassRewardClaims" to "anon";

grant truncate on table "public"."battlePassRewardClaims" to "anon";

grant update on table "public"."battlePassRewardClaims" to "anon";

grant delete on table "public"."battlePassRewardClaims" to "authenticated";

grant insert on table "public"."battlePassRewardClaims" to "authenticated";

grant references on table "public"."battlePassRewardClaims" to "authenticated";

grant select on table "public"."battlePassRewardClaims" to "authenticated";

grant trigger on table "public"."battlePassRewardClaims" to "authenticated";

grant truncate on table "public"."battlePassRewardClaims" to "authenticated";

grant update on table "public"."battlePassRewardClaims" to "authenticated";

grant delete on table "public"."battlePassRewardClaims" to "service_role";

grant insert on table "public"."battlePassRewardClaims" to "service_role";

grant references on table "public"."battlePassRewardClaims" to "service_role";

grant select on table "public"."battlePassRewardClaims" to "service_role";

grant trigger on table "public"."battlePassRewardClaims" to "service_role";

grant truncate on table "public"."battlePassRewardClaims" to "service_role";

grant update on table "public"."battlePassRewardClaims" to "service_role";

grant delete on table "public"."battlePassSeasons" to "anon";

grant insert on table "public"."battlePassSeasons" to "anon";

grant references on table "public"."battlePassSeasons" to "anon";

grant select on table "public"."battlePassSeasons" to "anon";

grant trigger on table "public"."battlePassSeasons" to "anon";

grant truncate on table "public"."battlePassSeasons" to "anon";

grant update on table "public"."battlePassSeasons" to "anon";

grant delete on table "public"."battlePassSeasons" to "authenticated";

grant insert on table "public"."battlePassSeasons" to "authenticated";

grant references on table "public"."battlePassSeasons" to "authenticated";

grant select on table "public"."battlePassSeasons" to "authenticated";

grant trigger on table "public"."battlePassSeasons" to "authenticated";

grant truncate on table "public"."battlePassSeasons" to "authenticated";

grant update on table "public"."battlePassSeasons" to "authenticated";

grant delete on table "public"."battlePassSeasons" to "service_role";

grant insert on table "public"."battlePassSeasons" to "service_role";

grant references on table "public"."battlePassSeasons" to "service_role";

grant select on table "public"."battlePassSeasons" to "service_role";

grant trigger on table "public"."battlePassSeasons" to "service_role";

grant truncate on table "public"."battlePassSeasons" to "service_role";

grant update on table "public"."battlePassSeasons" to "service_role";

grant delete on table "public"."battlePassTierRewards" to "anon";

grant insert on table "public"."battlePassTierRewards" to "anon";

grant references on table "public"."battlePassTierRewards" to "anon";

grant select on table "public"."battlePassTierRewards" to "anon";

grant trigger on table "public"."battlePassTierRewards" to "anon";

grant truncate on table "public"."battlePassTierRewards" to "anon";

grant update on table "public"."battlePassTierRewards" to "anon";

grant delete on table "public"."battlePassTierRewards" to "authenticated";

grant insert on table "public"."battlePassTierRewards" to "authenticated";

grant references on table "public"."battlePassTierRewards" to "authenticated";

grant select on table "public"."battlePassTierRewards" to "authenticated";

grant trigger on table "public"."battlePassTierRewards" to "authenticated";

grant truncate on table "public"."battlePassTierRewards" to "authenticated";

grant update on table "public"."battlePassTierRewards" to "authenticated";

grant delete on table "public"."battlePassTierRewards" to "service_role";

grant insert on table "public"."battlePassTierRewards" to "service_role";

grant references on table "public"."battlePassTierRewards" to "service_role";

grant select on table "public"."battlePassTierRewards" to "service_role";

grant trigger on table "public"."battlePassTierRewards" to "service_role";

grant truncate on table "public"."battlePassTierRewards" to "service_role";

grant update on table "public"."battlePassTierRewards" to "service_role";

grant delete on table "public"."mapPackLevels" to "anon";

grant insert on table "public"."mapPackLevels" to "anon";

grant references on table "public"."mapPackLevels" to "anon";

grant select on table "public"."mapPackLevels" to "anon";

grant trigger on table "public"."mapPackLevels" to "anon";

grant truncate on table "public"."mapPackLevels" to "anon";

grant update on table "public"."mapPackLevels" to "anon";

grant delete on table "public"."mapPackLevels" to "authenticated";

grant insert on table "public"."mapPackLevels" to "authenticated";

grant references on table "public"."mapPackLevels" to "authenticated";

grant select on table "public"."mapPackLevels" to "authenticated";

grant trigger on table "public"."mapPackLevels" to "authenticated";

grant truncate on table "public"."mapPackLevels" to "authenticated";

grant update on table "public"."mapPackLevels" to "authenticated";

grant delete on table "public"."mapPackLevels" to "service_role";

grant insert on table "public"."mapPackLevels" to "service_role";

grant references on table "public"."mapPackLevels" to "service_role";

grant select on table "public"."mapPackLevels" to "service_role";

grant trigger on table "public"."mapPackLevels" to "service_role";

grant truncate on table "public"."mapPackLevels" to "service_role";

grant update on table "public"."mapPackLevels" to "service_role";

grant delete on table "public"."mapPacks" to "anon";

grant insert on table "public"."mapPacks" to "anon";

grant references on table "public"."mapPacks" to "anon";

grant select on table "public"."mapPacks" to "anon";

grant trigger on table "public"."mapPacks" to "anon";

grant truncate on table "public"."mapPacks" to "anon";

grant update on table "public"."mapPacks" to "anon";

grant delete on table "public"."mapPacks" to "authenticated";

grant insert on table "public"."mapPacks" to "authenticated";

grant references on table "public"."mapPacks" to "authenticated";

grant select on table "public"."mapPacks" to "authenticated";

grant trigger on table "public"."mapPacks" to "authenticated";

grant truncate on table "public"."mapPacks" to "authenticated";

grant update on table "public"."mapPacks" to "authenticated";

grant delete on table "public"."mapPacks" to "service_role";

grant insert on table "public"."mapPacks" to "service_role";

grant references on table "public"."mapPacks" to "service_role";

grant select on table "public"."mapPacks" to "service_role";

grant trigger on table "public"."mapPacks" to "service_role";

grant truncate on table "public"."mapPacks" to "service_role";

grant update on table "public"."mapPacks" to "service_role";

grant delete on table "public"."playerSubscriptions" to "anon";

grant insert on table "public"."playerSubscriptions" to "anon";

grant references on table "public"."playerSubscriptions" to "anon";

grant select on table "public"."playerSubscriptions" to "anon";

grant trigger on table "public"."playerSubscriptions" to "anon";

grant truncate on table "public"."playerSubscriptions" to "anon";

grant update on table "public"."playerSubscriptions" to "anon";

grant delete on table "public"."playerSubscriptions" to "authenticated";

grant insert on table "public"."playerSubscriptions" to "authenticated";

grant references on table "public"."playerSubscriptions" to "authenticated";

grant select on table "public"."playerSubscriptions" to "authenticated";

grant trigger on table "public"."playerSubscriptions" to "authenticated";

grant truncate on table "public"."playerSubscriptions" to "authenticated";

grant update on table "public"."playerSubscriptions" to "authenticated";

grant delete on table "public"."playerSubscriptions" to "service_role";

grant insert on table "public"."playerSubscriptions" to "service_role";

grant references on table "public"."playerSubscriptions" to "service_role";

grant select on table "public"."playerSubscriptions" to "service_role";

grant trigger on table "public"."playerSubscriptions" to "service_role";

grant truncate on table "public"."playerSubscriptions" to "service_role";

grant update on table "public"."playerSubscriptions" to "service_role";


