ALTER TABLE "public"."battlePassSeasons"
ADD COLUMN IF NOT EXISTS "courseId" bigint;

CREATE TABLE IF NOT EXISTS "public"."battlePassCourses" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "title" text NOT NULL,
    "description" text,
    CONSTRAINT "battlePassCourses_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "public"."battlePassCourseEntries" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "courseId" bigint NOT NULL,
    "type" text NOT NULL,
    "refId" bigint NOT NULL,
    "sortOrder" integer NOT NULL DEFAULT 0,
    "rewardXp" integer NOT NULL DEFAULT 0,
    "rewardItemId" bigint,
    "rewardQuantity" integer NOT NULL DEFAULT 1,
    CONSTRAINT "battlePassCourseEntries_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "battlePassCourseEntries_type_check" CHECK (("type" = ANY (ARRAY['level'::text, 'mappack'::text]))),
    CONSTRAINT "battlePassCourseEntries_rewardQuantity_check" CHECK ("rewardQuantity" > 0)
);

CREATE TABLE IF NOT EXISTS "public"."battlePassCourseEntryProgress" (
    "entryId" bigint NOT NULL,
    "userID" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "completed" boolean NOT NULL DEFAULT false,
    "claimed" boolean NOT NULL DEFAULT false,
    "completedAt" timestamp with time zone,
    "claimedAt" timestamp with time zone,
    CONSTRAINT "battlePassCourseEntryProgress_pkey" PRIMARY KEY ("entryId", "userID")
);

ALTER TABLE ONLY "public"."battlePassSeasons"
    ADD CONSTRAINT "battlePassSeasons_courseId_fkey"
    FOREIGN KEY ("courseId") REFERENCES "public"."battlePassCourses"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."battlePassCourseEntries"
    ADD CONSTRAINT "battlePassCourseEntries_courseId_fkey"
    FOREIGN KEY ("courseId") REFERENCES "public"."battlePassCourses"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassCourseEntries"
    ADD CONSTRAINT "battlePassCourseEntries_rewardItemId_fkey"
    FOREIGN KEY ("rewardItemId") REFERENCES "public"."items"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."battlePassCourseEntryProgress"
    ADD CONSTRAINT "battlePassCourseEntryProgress_entryId_fkey"
    FOREIGN KEY ("entryId") REFERENCES "public"."battlePassCourseEntries"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassCourseEntryProgress"
    ADD CONSTRAINT "battlePassCourseEntryProgress_userID_fkey"
    FOREIGN KEY ("userID") REFERENCES "public"."players"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "battlePassCourseEntries_courseId_sortOrder_idx"
ON "public"."battlePassCourseEntries" USING btree ("courseId", "sortOrder");

CREATE INDEX IF NOT EXISTS "battlePassCourseEntryProgress_userID_idx"
ON "public"."battlePassCourseEntryProgress" USING btree ("userID");

ALTER TABLE "public"."battlePassCourses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassCourseEntries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassCourseEntryProgress" ENABLE ROW LEVEL SECURITY;
