CREATE TABLE IF NOT EXISTS "public"."lists" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "owner" uuid NOT NULL,
    "title" text NOT NULL,
    "description" text DEFAULT ''::text NOT NULL,
    "visibility" text DEFAULT 'private'::text NOT NULL,
    "tags" text[] DEFAULT '{}'::text[] NOT NULL,
    "levelCount" bigint DEFAULT '0'::bigint NOT NULL,
    CONSTRAINT "lists_title_check" CHECK (((length("title") >= 1) AND (length("title") <= 100))),
    CONSTRAINT "lists_visibility_check" CHECK (("visibility" = ANY (ARRAY['private'::text, 'unlisted'::text, 'public'::text])))
);


ALTER TABLE "public"."lists" OWNER TO "postgres";


ALTER TABLE "public"."lists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."lists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."listLevels" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "listId" bigint NOT NULL,
    "levelId" bigint NOT NULL,
    "addedBy" uuid NOT NULL
);


ALTER TABLE "public"."listLevels" OWNER TO "postgres";


ALTER TABLE "public"."listLevels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listLevels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."lists"
    ADD CONSTRAINT "lists_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."listLevels"
    ADD CONSTRAINT "listLevels_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."listLevels"
    ADD CONSTRAINT "list_levels_list_id_level_id_key" UNIQUE ("listId", "levelId");


CREATE INDEX IF NOT EXISTS "list_levels_list_id_idx" ON "public"."listLevels" USING btree ("listId");
CREATE INDEX IF NOT EXISTS "list_levels_level_id_idx" ON "public"."listLevels" USING btree ("levelId");
CREATE INDEX IF NOT EXISTS "lists_owner_idx" ON "public"."lists" USING btree ("owner");
CREATE INDEX IF NOT EXISTS "lists_visibility_idx" ON "public"."lists" USING btree ("visibility");


ALTER TABLE ONLY "public"."lists"
    ADD CONSTRAINT "lists_owner_fkey" FOREIGN KEY ("owner") REFERENCES "public"."players"("uid") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."listLevels"
    ADD CONSTRAINT "list_levels_added_by_fkey" FOREIGN KEY ("addedBy") REFERENCES "public"."players"("uid");


ALTER TABLE ONLY "public"."listLevels"
    ADD CONSTRAINT "list_levels_level_id_fkey" FOREIGN KEY ("levelId") REFERENCES "public"."levels"("id");


ALTER TABLE ONLY "public"."listLevels"
    ADD CONSTRAINT "list_levels_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;