-- Battle Pass Seasons table
CREATE TABLE IF NOT EXISTS "public"."battlePassSeasons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "start" timestamp with time zone NOT NULL,
    "end" timestamp with time zone NOT NULL,
    "isArchived" boolean DEFAULT false NOT NULL,
    "premiumPrice" bigint DEFAULT '149000'::bigint NOT NULL
);

ALTER TABLE "public"."battlePassSeasons" OWNER TO "postgres";

ALTER TABLE "public"."battlePassSeasons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battlePassSeasons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battlePassSeasons"
    ADD CONSTRAINT "battlePassSeasons_pkey" PRIMARY KEY ("id");

-- Battle Pass Levels (Extreme Demons) - 3 per season
CREATE TABLE IF NOT EXISTS "public"."battlePassLevels" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "seasonId" bigint NOT NULL,
    "levelID" bigint NOT NULL,
    "xp" bigint DEFAULT '1000'::bigint NOT NULL,
    "minProgressXp" bigint DEFAULT '500'::bigint NOT NULL,
    "minProgress" bigint DEFAULT '50'::bigint NOT NULL
);

ALTER TABLE "public"."battlePassLevels" OWNER TO "postgres";

ALTER TABLE "public"."battlePassLevels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battlePassLevels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battlePassLevels"
    ADD CONSTRAINT "battlePassLevels_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."battlePassLevels"
    ADD CONSTRAINT "battlePassLevels_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "public"."battlePassSeasons"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassLevels"
    ADD CONSTRAINT "battlePassLevels_levelID_fkey" FOREIGN KEY ("levelID") REFERENCES "public"."levels"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Map Packs - 12 per season
CREATE TABLE IF NOT EXISTS "public"."battlePassMapPacks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "seasonId" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "difficulty" "text" NOT NULL,
    "xp" bigint NOT NULL,
    "unlockWeek" bigint NOT NULL,
    "order" bigint DEFAULT '0'::bigint NOT NULL,
    CONSTRAINT "battlePassMapPacks_difficulty_check" CHECK (("difficulty" = ANY (ARRAY['easier'::"text", 'harder'::"text", 'medium_demon'::"text", 'insane_demon'::"text"])))
);

ALTER TABLE "public"."battlePassMapPacks" OWNER TO "postgres";

ALTER TABLE "public"."battlePassMapPacks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battlePassMapPacks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battlePassMapPacks"
    ADD CONSTRAINT "battlePassMapPacks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."battlePassMapPacks"
    ADD CONSTRAINT "battlePassMapPacks_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "public"."battlePassSeasons"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Map Pack Levels - 3-5 levels per pack
CREATE TABLE IF NOT EXISTS "public"."battlePassMapPackLevels" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "mapPackId" bigint NOT NULL,
    "levelID" bigint NOT NULL,
    "order" bigint DEFAULT '0'::bigint NOT NULL
);

ALTER TABLE "public"."battlePassMapPackLevels" OWNER TO "postgres";

ALTER TABLE "public"."battlePassMapPackLevels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battlePassMapPackLevels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battlePassMapPackLevels"
    ADD CONSTRAINT "battlePassMapPackLevels_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."battlePassMapPackLevels"
    ADD CONSTRAINT "battlePassMapPackLevels_mapPackId_fkey" FOREIGN KEY ("mapPackId") REFERENCES "public"."battlePassMapPacks"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassMapPackLevels"
    ADD CONSTRAINT "battlePassMapPackLevels_levelID_fkey" FOREIGN KEY ("levelID") REFERENCES "public"."levels"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Player Progress
CREATE TABLE IF NOT EXISTS "public"."battlePassProgress" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "seasonId" bigint NOT NULL,
    "userID" "uuid" NOT NULL,
    "xp" bigint DEFAULT '0'::bigint NOT NULL,
    "isPremium" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."battlePassProgress" OWNER TO "postgres";

ALTER TABLE ONLY "public"."battlePassProgress"
    ADD CONSTRAINT "battlePassProgress_pkey" PRIMARY KEY ("seasonId", "userID");

ALTER TABLE ONLY "public"."battlePassProgress"
    ADD CONSTRAINT "battlePassProgress_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "public"."battlePassSeasons"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassProgress"
    ADD CONSTRAINT "battlePassProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES "public"."players"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Level Progress (for tracking individual level progress)
CREATE TABLE IF NOT EXISTS "public"."battlePassLevelProgress" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "battlePassLevelId" bigint NOT NULL,
    "userID" "uuid" NOT NULL,
    "progress" bigint DEFAULT '0'::bigint NOT NULL,
    "minProgressClaimed" boolean DEFAULT false NOT NULL,
    "completionClaimed" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."battlePassLevelProgress" OWNER TO "postgres";

ALTER TABLE ONLY "public"."battlePassLevelProgress"
    ADD CONSTRAINT "battlePassLevelProgress_pkey" PRIMARY KEY ("battlePassLevelId", "userID");

ALTER TABLE ONLY "public"."battlePassLevelProgress"
    ADD CONSTRAINT "battlePassLevelProgress_battlePassLevelId_fkey" FOREIGN KEY ("battlePassLevelId") REFERENCES "public"."battlePassLevels"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassLevelProgress"
    ADD CONSTRAINT "battlePassLevelProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES "public"."players"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Map Pack Progress
CREATE TABLE IF NOT EXISTS "public"."battlePassMapPackProgress" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "mapPackId" bigint NOT NULL,
    "userID" "uuid" NOT NULL,
    "completedLevels" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    "claimed" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."battlePassMapPackProgress" OWNER TO "postgres";

ALTER TABLE ONLY "public"."battlePassMapPackProgress"
    ADD CONSTRAINT "battlePassMapPackProgress_pkey" PRIMARY KEY ("mapPackId", "userID");

ALTER TABLE ONLY "public"."battlePassMapPackProgress"
    ADD CONSTRAINT "battlePassMapPackProgress_mapPackId_fkey" FOREIGN KEY ("mapPackId") REFERENCES "public"."battlePassMapPacks"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassMapPackProgress"
    ADD CONSTRAINT "battlePassMapPackProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES "public"."players"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Tier Rewards - Configures what rewards are given at each tier
CREATE TABLE IF NOT EXISTS "public"."battlePassTierRewards" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "seasonId" bigint NOT NULL,
    "tier" bigint NOT NULL,
    "isPremium" boolean DEFAULT false NOT NULL,
    "itemId" bigint NOT NULL,
    "quantity" bigint DEFAULT '1'::bigint NOT NULL,
    "description" "text"
);

ALTER TABLE "public"."battlePassTierRewards" OWNER TO "postgres";

ALTER TABLE "public"."battlePassTierRewards" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battlePassTierRewards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battlePassTierRewards"
    ADD CONSTRAINT "battlePassTierRewards_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."battlePassTierRewards"
    ADD CONSTRAINT "battlePassTierRewards_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "public"."battlePassSeasons"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassTierRewards"
    ADD CONSTRAINT "battlePassTierRewards_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Reward Claims - Tracks which tier rewards a player has claimed
CREATE TABLE IF NOT EXISTS "public"."battlePassRewardClaims" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "rewardId" bigint NOT NULL,
    "userID" "uuid" NOT NULL
);

ALTER TABLE "public"."battlePassRewardClaims" OWNER TO "postgres";

ALTER TABLE ONLY "public"."battlePassRewardClaims"
    ADD CONSTRAINT "battlePassRewardClaims_pkey" PRIMARY KEY ("rewardId", "userID");

ALTER TABLE ONLY "public"."battlePassRewardClaims"
    ADD CONSTRAINT "battlePassRewardClaims_rewardId_fkey" FOREIGN KEY ("rewardId") REFERENCES "public"."battlePassTierRewards"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassRewardClaims"
    ADD CONSTRAINT "battlePassRewardClaims_userID_fkey" FOREIGN KEY ("userID") REFERENCES "public"."players"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

-- Enable Row Level Security
ALTER TABLE "public"."battlePassSeasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassLevels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassMapPacks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassMapPackLevels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassLevelProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassMapPackProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassTierRewards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassRewardClaims" ENABLE ROW LEVEL SECURITY;

-- Create policies for read access
CREATE POLICY "Enable read access for all users" ON "public"."battlePassSeasons" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."battlePassLevels" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."battlePassMapPacks" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."battlePassMapPackLevels" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."battlePassTierRewards" FOR SELECT USING (true);

-- Grant permissions
GRANT ALL ON TABLE "public"."battlePassSeasons" TO "anon";
GRANT ALL ON TABLE "public"."battlePassSeasons" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassSeasons" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassLevels" TO "anon";
GRANT ALL ON TABLE "public"."battlePassLevels" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassLevels" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassMapPacks" TO "anon";
GRANT ALL ON TABLE "public"."battlePassMapPacks" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassMapPacks" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassMapPackLevels" TO "anon";
GRANT ALL ON TABLE "public"."battlePassMapPackLevels" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassMapPackLevels" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassProgress" TO "anon";
GRANT ALL ON TABLE "public"."battlePassProgress" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassProgress" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassLevelProgress" TO "anon";
GRANT ALL ON TABLE "public"."battlePassLevelProgress" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassLevelProgress" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassMapPackProgress" TO "anon";
GRANT ALL ON TABLE "public"."battlePassMapPackProgress" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassMapPackProgress" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassTierRewards" TO "anon";
GRANT ALL ON TABLE "public"."battlePassTierRewards" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassTierRewards" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassRewardClaims" TO "anon";
GRANT ALL ON TABLE "public"."battlePassRewardClaims" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassRewardClaims" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battlePassSeasons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battlePassSeasons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battlePassSeasons_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battlePassLevels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battlePassLevels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battlePassLevels_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battlePassMapPacks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battlePassMapPacks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battlePassMapPacks_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battlePassMapPackLevels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battlePassMapPackLevels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battlePassMapPackLevels_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battlePassTierRewards_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battlePassTierRewards_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battlePassTierRewards_id_seq" TO "service_role";

-- Battle Pass Missions - Missions to clear level or map pack with JSONB condition
CREATE TABLE IF NOT EXISTS "public"."battlePassMissions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "seasonId" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "condition" jsonb NOT NULL,
    "xp" bigint NOT NULL,
    "order" bigint DEFAULT '0'::bigint NOT NULL
);

ALTER TABLE "public"."battlePassMissions" OWNER TO "postgres";

ALTER TABLE "public"."battlePassMissions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battlePassMissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battlePassMissions"
    ADD CONSTRAINT "battlePassMissions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."battlePassMissions"
    ADD CONSTRAINT "battlePassMissions_seasonId_fkey" FOREIGN KEY ("seasonId") REFERENCES "public"."battlePassSeasons"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Mission Rewards - Rewards for completing a mission
CREATE TABLE IF NOT EXISTS "public"."battlePassMissionRewards" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "missionId" bigint NOT NULL,
    "itemId" bigint NOT NULL,
    "quantity" bigint DEFAULT '1'::bigint NOT NULL,
    "expireAfter" bigint
);

ALTER TABLE "public"."battlePassMissionRewards" OWNER TO "postgres";

ALTER TABLE "public"."battlePassMissionRewards" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."battlePassMissionRewards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."battlePassMissionRewards"
    ADD CONSTRAINT "battlePassMissionRewards_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."battlePassMissionRewards"
    ADD CONSTRAINT "battlePassMissionRewards_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "public"."battlePassMissions"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassMissionRewards"
    ADD CONSTRAINT "battlePassMissionRewards_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "public"."items"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- Battle Pass Mission Claims - Tracks which missions a player has claimed (each can only be claimed once)
CREATE TABLE IF NOT EXISTS "public"."battlePassMissionClaims" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "missionId" bigint NOT NULL,
    "userID" "uuid" NOT NULL
);

ALTER TABLE "public"."battlePassMissionClaims" OWNER TO "postgres";

ALTER TABLE ONLY "public"."battlePassMissionClaims"
    ADD CONSTRAINT "battlePassMissionClaims_pkey" PRIMARY KEY ("missionId", "userID");

ALTER TABLE ONLY "public"."battlePassMissionClaims"
    ADD CONSTRAINT "battlePassMissionClaims_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "public"."battlePassMissions"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassMissionClaims"
    ADD CONSTRAINT "battlePassMissionClaims_userID_fkey" FOREIGN KEY ("userID") REFERENCES "public"."players"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

-- Enable Row Level Security for mission tables
ALTER TABLE "public"."battlePassMissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassMissionRewards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."battlePassMissionClaims" ENABLE ROW LEVEL SECURITY;

-- Create policies for read access
CREATE POLICY "Enable read access for all users" ON "public"."battlePassMissions" FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."battlePassMissionRewards" FOR SELECT USING (true);

-- Grant permissions for mission tables
GRANT ALL ON TABLE "public"."battlePassMissions" TO "anon";
GRANT ALL ON TABLE "public"."battlePassMissions" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassMissions" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassMissionRewards" TO "anon";
GRANT ALL ON TABLE "public"."battlePassMissionRewards" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassMissionRewards" TO "service_role";

GRANT ALL ON TABLE "public"."battlePassMissionClaims" TO "anon";
GRANT ALL ON TABLE "public"."battlePassMissionClaims" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassMissionClaims" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battlePassMissions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battlePassMissions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battlePassMissions_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."battlePassMissionRewards_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."battlePassMissionRewards_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."battlePassMissionRewards_id_seq" TO "service_role";

-- Battle Pass Mission Progress - Tracks player mission completion status
CREATE TABLE IF NOT EXISTS "public"."battlePassMissionProgress" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "missionId" bigint NOT NULL,
    "userID" "uuid" NOT NULL,
    "completed" boolean DEFAULT false NOT NULL
);

ALTER TABLE "public"."battlePassMissionProgress" OWNER TO "postgres";

ALTER TABLE ONLY "public"."battlePassMissionProgress"
    ADD CONSTRAINT "battlePassMissionProgress_pkey" PRIMARY KEY ("missionId", "userID");

ALTER TABLE ONLY "public"."battlePassMissionProgress"
    ADD CONSTRAINT "battlePassMissionProgress_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "public"."battlePassMissions"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."battlePassMissionProgress"
    ADD CONSTRAINT "battlePassMissionProgress_userID_fkey" FOREIGN KEY ("userID") REFERENCES "public"."players"("uid") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."battlePassMissionProgress" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."battlePassMissionProgress" TO "anon";
GRANT ALL ON TABLE "public"."battlePassMissionProgress" TO "authenticated";
GRANT ALL ON TABLE "public"."battlePassMissionProgress" TO "service_role";
