ALTER TABLE "public"."listLeaderboardRefreshes"
    ADD COLUMN IF NOT EXISTS "totalRecords" bigint DEFAULT '0'::bigint NOT NULL;


ALTER TABLE "public"."listLeaderboardEntries"
    ADD COLUMN IF NOT EXISTS "listId" bigint;


UPDATE "public"."listLeaderboardEntries" AS "entries"
SET "listId" = "refreshes"."listId"
FROM "public"."listLeaderboardRefreshes" AS "refreshes"
WHERE "entries"."refreshId" = "refreshes"."id"
    AND "entries"."listId" IS NULL;


WITH "latest_refreshes" AS (
    SELECT DISTINCT ON ("listId")
        "id",
        "listId"
    FROM "public"."listLeaderboardRefreshes"
    ORDER BY "listId", "lastRefreshedAt" DESC, "id" DESC
)
DELETE FROM "public"."listLeaderboardEntries" AS "entries"
USING "public"."listLeaderboardRefreshes" AS "refreshes", "latest_refreshes"
WHERE "entries"."refreshId" = "refreshes"."id"
    AND "refreshes"."listId" = "latest_refreshes"."listId"
    AND "refreshes"."id" <> "latest_refreshes"."id";


WITH "latest_refreshes" AS (
    SELECT DISTINCT ON ("listId")
        "id",
        "listId"
    FROM "public"."listLeaderboardRefreshes"
    ORDER BY "listId", "lastRefreshedAt" DESC, "id" DESC
)
DELETE FROM "public"."listLeaderboardRefreshes" AS "refreshes"
USING "latest_refreshes"
WHERE "refreshes"."listId" = "latest_refreshes"."listId"
    AND "refreshes"."id" <> "latest_refreshes"."id";


ALTER TABLE "public"."listLeaderboardEntries"
    ALTER COLUMN "listId" SET NOT NULL;


ALTER TABLE ONLY "public"."listLeaderboardRefreshes"
    ADD CONSTRAINT "list_leaderboard_refreshes_list_id_key" UNIQUE ("listId");


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    DROP CONSTRAINT "list_leaderboard_entries_refresh_id_rank_key";


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    DROP CONSTRAINT "list_leaderboard_entries_refresh_id_uid_key";


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    DROP CONSTRAINT "list_leaderboard_entries_refresh_id_fkey";


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "list_leaderboard_entries_list_id_rank_key" UNIQUE ("listId", "rank");


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "list_leaderboard_entries_list_id_uid_key" UNIQUE ("listId", "uid");


ALTER TABLE ONLY "public"."listLeaderboardEntries"
    ADD CONSTRAINT "list_leaderboard_entries_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;


DROP INDEX "public"."list_leaderboard_entries_refresh_id_rank_idx";


CREATE INDEX "list_leaderboard_entries_list_id_rank_idx"
    ON "public"."listLeaderboardEntries" USING "btree" ("listId", "rank");


ALTER TABLE "public"."listLeaderboardEntries"
    DROP COLUMN "refreshId";


CREATE TABLE IF NOT EXISTS "public"."listLeaderboardRecordEntries" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "listId" bigint NOT NULL,
    "uid" "uuid" NOT NULL,
    "levelId" bigint NOT NULL,
    "point" double precision NOT NULL,
    "no" bigint NOT NULL,
    CONSTRAINT "listLeaderboardRecordEntries_no_check" CHECK (("no" > 0))
);


ALTER TABLE "public"."listLeaderboardRecordEntries" OWNER TO "postgres";


ALTER TABLE "public"."listLeaderboardRecordEntries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."listLeaderboardRecordEntries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."listLeaderboardRecordEntries"
    ADD CONSTRAINT "listLeaderboardRecordEntries_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."listLeaderboardRecordEntries"
    ADD CONSTRAINT "list_leaderboard_record_entries_list_id_no_key" UNIQUE ("listId", "no");


ALTER TABLE ONLY "public"."listLeaderboardRecordEntries"
    ADD CONSTRAINT "list_leaderboard_record_entries_list_id_uid_level_id_key" UNIQUE ("listId", "uid", "levelId");


ALTER TABLE ONLY "public"."listLeaderboardRecordEntries"
    ADD CONSTRAINT "list_leaderboard_record_entries_list_id_fkey" FOREIGN KEY ("listId") REFERENCES "public"."lists"("id") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."listLeaderboardRecordEntries"
    ADD CONSTRAINT "list_leaderboard_record_entries_level_id_fkey" FOREIGN KEY ("levelId") REFERENCES "public"."levels"("id") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."listLeaderboardRecordEntries"
    ADD CONSTRAINT "list_leaderboard_record_entries_uid_fkey" FOREIGN KEY ("uid") REFERENCES "public"."players"("uid") ON DELETE CASCADE;


CREATE INDEX "list_leaderboard_record_entries_list_id_no_idx"
    ON "public"."listLeaderboardRecordEntries" USING "btree" ("listId", "no");