name: Trigger auto deployment for dlvn-api-v3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/dlvn-api-v3-AutoDeployTrigger-cd889385-5981-49fd-8f36-081832760adb.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DLVNAPIV3_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.DLVNAPIV3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DLVNAPIV3_REGISTRY_PASSWORD }}
          containerAppName: dlvn-api-v3
          resourceGroup: DefaultResourceGroup-SEA
          imageToBuild: ghcr.io/nampe286/dlvn-api-v3-ghcr:latest
          
            

     

